Change value for unused pin to -1
avrdudes/avrdude pull request #1231
Opened 2022-12-19 22:03 UTC by wijnen

This fixes bug #1228, that gpio 0 could not be used by the linuxgpio system.

These changes need to be checked on hardware, not only with linuxgpio, but also with other systems, because they change the pin encoding for all systems, so they have the potential to break them.

2022-12-19 22:06 UTC, dl8dtl commented
I'm all for it – my only remark: I'd appreciate something like `#define NO_PIN (-1)`.

2022-12-21 12:13 UTC, stefanrueger requested changes
Thanks for this PR! The logic is neat and the PR is easy to follow.

Is it necessary to change the type of `pinno[]` from `unsigned int` to `int`? That kind of change is difficult to handle and to review as *all* other use of `pinno` needs checking whether assumption `>= 0` was used. This has generated 10 `-Wpointer-sign` `-Wsign-compare` gcc compiler warnings. Besides, people who have used the the avrdude library may find unintended changes in their applications.

Unless there is a good reason for changing the type, I would suggest to keep the type `unsigned int` and simply define
```
#define NO_PIN            (-1U) // Magic pinno[] value for unused pins
```
That should do the trick. Note that `-1U` is a perfectly valid unsigned number (it computes to 0x0FFFFffffU), and note also that it is customary to put #defined expressions in brackets to avoid operator precedence or replacement surprises.

Please just push another commit to this branch rather than force-pushing a different branch, so we see the difference and don't have review from start. We can squash & merge if it's important to you this appear as one commit in git main.

Last question: have you checked all uses of `pinno[]` to verify that no other use thinks `0` means unused pin? (I haven't)

Thanks again for bringing this problem to our attention and for solving it!

2022-12-21 12:30 UTC, dl8dtl commented
It's also possible to use some distinct huge value instead of -1, e.g. 0x8000 or such. That's for sure unreasonably high for any real pin number, but avoids the signedness issue Stefan mentioned.

2022-12-21 13:07 UTC, stefanrueger commented
> It's also possible to use some distinct huge value instead of -1, e.g. 0x8000 or such. That's for sure unreasonably high for any real pin number, but avoids the signedness issue Stefan mentioned.

Correct. The smallest "represesentative" for undefined pinno is (PIN_MAX+1U), but it doesn't matter which number outside the valid range is used.  Instead  `!= NO_PIN` comparisons one could use  `<= PIN_MAX`, which is actually a *safer* assertion that the pin number is *actually* in the valid allowed unsigned range.  Instead of `== NO_PIN` comparisons one could use `> PIN_MAX` (again a *safer* comparison). Both assumes `pinno[]` stays `unsigned int` which is recommended to save work on silencing compiler warnings, work for reviews and to not surprise anyone with an application that might rely on the original type chosen in libavrdude.

2022-12-21 13:28 UTC, stefanrueger commented
| the signedness issue Stefan mentioned

The issue is not the -1 for NO_PIN, the issue is that `pinno[]` was changed from `unsigned int` to `int`. *That* alone creates the 10 compiler warnings and causes other headaches.

2022-12-23 13:05 UTC, stefanrueger commented
OK, I have pushed commits to keep `pinno[]` unsigned, changed the definition of `NO_PIN` to the smallest invalid pin number, and reviewed all usages of `pinno[]`. Found a pre-existing error where a the highest foreseen pin number `PIN_MAX` would have been overlooked and a misleading tab indent. Fixed these two things, too.

@wijnen The intended functionality of the PR should remain unchanged, but please test and confirm.

Other than that I'd be happy for this PR to be merged (or squash & merged if @wijnen prefers).

2022-12-23 13:11 UTC, stefanrueger approved these changes
All should be OK now.

The error from the github runner is unrelated to this PR (failing to install prerequisites) and that happens from time to time.

2022-12-23 13:28 UTC, mcuee commented
> The error from the github runner is unrelated to this PR (failing to install prerequisites) and that happens from time to time

Now it seems to be a Homebrew Python problem. Previously the issues are more with temporary download server problem.
```
==> Pouring imagemagick--7.1.0-55.monterey.bottle.tar.gz
🍺  /usr/local/Cellar/imagemagick/7.1.0-55: 807 files, 28.7MB
==> Running `brew cleanup imagemagick`...
Removing: /usr/local/Cellar/imagemagick/7.1.0-54... (807 files, 28.7MB)
Removing: /Users/runner/Library/Caches/Homebrew/imagemagick--7.1.0-54... (10.2MB)
==> Upgrading python@3.10
  3.10.8 -> 3.10.9 

==> Pouring python@3.10--3.10.9.monterey.bottle.tar.gz
Error: The `brew link` step did not complete successfully
The formula built, but is not symlinked into /usr/local
Could not symlink bin/2to3
Target /usr/local/bin/2to3
already exists. You may want to remove it:
  rm '/usr/local/bin/2to3'

To force the link and overwrite all conflicting files:
  brew link --overwrite python@3.10

To list all files that would be deleted:
  brew link --overwrite --dry-run python@3.10

Possible conflicting files are:
/usr/local/bin/2to3 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/2to3
/usr/local/bin/idle3 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/idle3
/usr/local/bin/pydoc3 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/pydoc3
/usr/local/bin/python3 -> /Library/Frameworks/Python.framework/Versions/3.11/bin/python3
/usr/local/bin/python3-config -> /Library/Frameworks/Python.framework/Versions/3.11/bin/python3-config

```

2022-12-24 00:40 UTC, mcuee commented
@stefanrueger and @wijnen 

Just wondering if linuxspi is affected by the original issue or not. Is it also taken care of by this PR?

2022-12-24 02:33 UTC, stefanrueger commented
| Just wondering if linuxspi is affected by the original issue or not. Is it also taken care of by this PR?

This PR basically frees 0 as valid pin number when used through the (old) `pinno[]` structures. I looked at all usage of `pinno[]` and could not detect an obvious problem of this affecting something else negatively.

2022-12-25 10:27 UTC, mcuee commented
I this case, this PR can be merged even though I do not have the chance to carry out the tests on real hardware.

2022-12-25 10:29 UTC, mcuee commented
@dl8dtl and @stefanrueger 

But in the end, I am okay either way: to merge this PR for 7.1 release or wait after 7.1 release.

2022-12-25 11:11 UTC, pzygielo commented
For consistency - can the PR title be updated?

2022-12-25 12:10 UTC, mcuee commented
> For consistency - can the PR title be updated?

Changed. Hopefully the change is clear now.

2022-12-26 09:34 UTC, mcuee commented
@stefanrueger and @wijnen 

I got the setup to test this PR. I think there is an issue with this PR that it is too verbose.
* https://github.com/avrdudes/avrdude/issues/1228#issuecomment-1365035577

2022-12-26 10:31 UTC, mcuee commented
My issue of super verbose output has nothing to do with this PR. No idea why it is trigged, probably due to my change to `boot/config.txt` even though I have reverted the changes and reboot.

```
pi@raspberrypi:~/Desktop/build/avr/avrdude_bin $ ./avrdude_pr1231 -C avrdude_gpio_0.conf -c linuxgpio -p m328p -U flash:w:blinky_m328p_with_bootloader.hex:i
...
...

Reading | ################################################## | 99% 8.35 s 0110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110110Reading | ################################################## | 100% 8.44 s 

avrdude_pr1231: 32768 bytes of flash verified
11
avrdude_pr1231 done.  Thank you.

pi@raspberrypi:~/Desktop/build/avr/avrdude_bin $ ./avrdude_pr1231 -c urclock -P /dev/ttyUSB0 -p m328p

avrdude_pr1231: AVR device initialized and ready to accept instructions
avrdude_pr1231: device signature = 0x1e950f (probably m328p)

avrdude_pr1231 done.  Thank you.
```

2022-12-26 10:35 UTC, mcuee commented
Terminal mode is also working.

```
pi@raspberrypi:~/Desktop/build/avr/avrdude_bin $ ./avrdude_pr1231 -C avrdude_gpio_0.conf -c linuxgpio -p m328p -t

11110avrdude_pr1231: AVR device initialized and ready to accept instructions
011011011avrdude_pr1231: device signature = 0x1e950f (probably m328p)
avrdude> dump lfuse

Reading | ################################################## | 100% 0.00 s 1

0000  f7                                                |.               |

avrdude> dump hfuse

Reading | ################################################## | 100% 0.00 s 1

0000  d6                                                |.               |

avrdude> dump efuse

Reading | ################################################## | 100% 0.00 s 1

0000  fd                                                |.               |

avrdude> dump flash 0 0x10

Reading | ################################################## | 100% 0.01 s 1111

0000  0c 94 5c 00 0c 94 6e 00  0c 94 6e 00 0c 94 6e 00  | .\. .n. .n. .n.|

avrdude> dump eeprom 0 0x10

Reading | ################################################## | 100% 0.01 s 1111

0000  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|

avrdude> dump flash 0x7e00 0x10

Reading | ################################################## | 100% 0.01 s 1111

7e00  11 24 84 b7 14 be 81 ff  f0 d0 85 e0 80 93 81 00  |.$..............|

avrdude> dump flash 0x7d00 0x10

Reading | ################################################## | 100% 0.01 s 1111

7d00  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|

avrdude> dump flash 0x7dc0 0x40

Reading | ################################################## | 100% 0.04 s 1111

7dc0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
7dd0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
7de0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|
7df0  ff ff ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |................|

avrdude> write eeprom 0 0xaa 0x55
1
Writing | ################################################## | 100% 0.01 s 1010110110110110110110111011011010110110110110110110111011

avrdude> flush
avrdude> dump eeprom 0 0x10

Reading | ################################################## | 100% 0.01 s 1111

0000  aa 55 ff ff ff ff ff ff  ff ff ff ff ff ff ff ff  |.U..............|

avrdude> quit
avrdude> 1
avrdude_pr1231 done.  Thank you.


```

2022-12-26 10:56 UTC, mcuee commented
I also tested out `linuxspi` with the RESET pin set to GPIO_0 and it works fine as well.

Configuration:
```
# This programmer bitbangs GPIO lines using the Linux sysfs GPIO interface
#
# To enable it set the configuration below to match the GPIO lines connected
# to the relevant ISP header pins and uncomment the entry definition. In case
# you don't have the required permissions to edit this system wide config
# file put the entry in a separate <your name>.conf file and use it with
# -C+<your name>.conf on the command line.
#
# To check if your avrdude build has support for the linuxgpio programmer
# compiled in, use -c?type on the command line and look for linuxgpio in the
# list. If it's not available you need pass the --enable-linuxgpio=yes option
# to configure and recompile avrdude.
#
#
# #------------------------------------------------------------
# # linuxgpio
# #------------------------------------------------------------
#
programmer
    id                   = "linuxgpio";
    desc                 = "Use the Linux sysfs interface to bitbang GPIO lines";
    type                 = "linuxgpio";
    prog_modes           = PM_ISP;
    reset                = 0;
    sck                  = 11;
    sdo                  = 10;
    sdi                  = 9;
;

#------------------------------------------------------------
# linuxspi
#------------------------------------------------------------

# This programmer uses the built in linux SPI bus devices to program an
# attached AVR. The reset pin must be attached to a GPIO pin that
# is otherwise unused (see gpioinfo(1)); the SPI bus CE pins are not
# suitable since they would release /RESET too early.
#

programmer
    id                     = "linuxspi";
    desc                   = "Use Linux SPI device in /dev/spidev*";
    type                   = "linuxspi";
    prog_modes             = PM_TPI | PM_ISP;
    connection_type        = spi;
    reset                  = 0;    # Pi GPIO number
;
```

Run log:
```
pi@raspberrypi:~/Desktop/build/avr/avrdude_bin $ ./avrdude_pr1231 -C avrdude_gpio_0.conf -c linuxspi -p m328p -v

avrdude_pr1231: Version 7.0-20221223 (184c62c)
                Copyright the AVRDUDE authors;
                see https://github.com/avrdudes/avrdude/blob/main/AUTHORS

                System wide configuration file is /home/pi/Desktop/build/avr/avrdude_bin/avrdude_gpio_0.conf
                User configuration file is /home/pi/.avrduderc
                User configuration file does not exist or is not a regular file, skipping

                Using Port                    : /dev/spidev0.0:/dev/gpiochip0
                Using Programmer              : linuxspi
avrdude_pr1231: defaulting bit clock to 200 kHz
                AVR Part                      : ATmega328P
                Chip Erase delay              : 9000 us
                PAGEL                         : PD7
                BS2                           : PC2
                RESET disposition             : possible i/o
                RETRY pulse                   : SCK
                Serial program mode           : yes
                Parallel program mode         : yes
                Timeout                       : 200
                StabDelay                     : 100
                CmdexeDelay                   : 25
                SyncLoops                     : 32
                PollIndex                     : 3
                PollValue                     : 0x53
                Memory Detail                 :

                                                  Block Poll               Page                       Polled
                  Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
                  ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
                  eeprom                 65    20     4    0 no       1024    4      0  3600  3600 0xff 0xff
                  flash                  65     6   128    0 yes     32768  128    256  4500  4500 0xff 0xff
                  lfuse                   0     0     0    0 no          1    1      0  4500  4500 0x00 0x00
                  hfuse                   0     0     0    0 no          1    1      0  4500  4500 0x00 0x00
                  efuse                   0     0     0    0 no          1    1      0  4500  4500 0x00 0x00
                  lock                    0     0     0    0 no          1    1      0  4500  4500 0x00 0x00
                  signature               0     0     0    0 no          3    1      0     0     0 0x00 0x00
                  calibration             0     0     0    0 no          1    1      0     0     0 0x00 0x00

                Programmer Type : linuxspi
                Description     : Use Linux SPI device in /dev/spidev*

avrdude_pr1231: AVR device initialized and ready to accept instructions
avrdude_pr1231: device signature = 0x1e950f (probably m328p)

avrdude_pr1231 done.  Thank you.

pi@raspberrypi:~/Desktop/build/avr/avrdude_bin $ ./avrdude_pr1231 -C avrdude_gpio_0.conf -c linuxspi -p m328p -U ./blinky_m328p_with_bootloader.hex 

avrdude_pr1231: AVR device initialized and ready to accept instructions
avrdude_pr1231: device signature = 0x1e950f (probably m328p)
avrdude_pr1231: Note: flash memory has been specified, an erase cycle will be performed.
                To disable this feature, specify the -D option.
avrdude_pr1231: erasing chip
avrdude_pr1231: reading input file ./blinky_m328p_with_bootloader.hex for flash
                with 32768 bytes in 1 section within [0, 0x7fff]
                using 256 pages and 0 pad bytes
avrdude_pr1231: writing 32768 bytes flash ...

Writing | ################################################## | 100% 11.51 s 

avrdude_pr1231: 32768 bytes of flash written
avrdude_pr1231: verifying flash memory against ./blinky_m328p_with_bootloader.hex

Reading | ################################################## | 100% 10.31 s 

avrdude_pr1231: 32768 bytes of flash verified

avrdude_pr1231 done.  Thank you.


```

2022-12-26 12:49 UTC, mcuee commented
> My issue of super verbose output has nothing to do with this PR. No idea why it is trigged, probably due to my change to boot/config.txt even though I have reverted the changes and reboot.

Hmm, I just created a new setup for my Raspberry Pi 400 and it is the same.

```
pi@raspberrypi:~/build/avr/avrdude_bin $ ./avrdude_pr1231 -C avrdude_gpio_0.conf -c linuxgpio -p m328p -v

avrdude_pr1231: Version 7.0-20221223 (184c62c)
                Copyright the AVRDUDE authors;
                see https://github.com/avrdudes/avrdude/blob/main/AUTHORS

                System wide configuration file is /home/pi/build/avr/avrdude_bin/avrdude_gpio_0.conf
                User configuration file is /home/pi/.avrduderc
                User configuration file does not exist or is not a regular file, skipping

                Using Port                    : /dev/parport0
                Using Programmer              : linuxgpio
                AVR Part                      : ATmega328P
                Chip Erase delay              : 9000 us
                PAGEL                         : PD7
                BS2                           : PC2
                RESET disposition             : possible i/o
                RETRY pulse                   : SCK
                Serial program mode           : yes
                Parallel program mode         : yes
                Timeout                       : 200
                StabDelay                     : 100
                CmdexeDelay                   : 25
                SyncLoops                     : 32
                PollIndex                     : 3
                PollValue                     : 0x53
                Memory Detail                 :

                                                  Block Poll               Page                       Polled
                  Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
                  ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
                  eeprom                 65    20     4    0 no       1024    4      0  3600  3600 0xff 0xff
                  flash                  65     6   128    0 yes     32768  128    256  4500  4500 0xff 0xff
                  lfuse                   0     0     0    0 no          1    1      0  4500  4500 0x00 0x00
                  hfuse                   0     0     0    0 no          1    1      0  4500  4500 0x00 0x00
                  efuse                   0     0     0    0 no          1    1      0  4500  4500 0x00 0x00
                  lock                    0     0     0    0 no          1    1      0  4500  4500 0x00 0x00
                  signature               0     0     0    0 no          3    1      0     0     0 0x00 0x00
                  calibration             0     0     0    0 no          1    1      0     0     0 0x00 0x00

                Programmer Type : linuxgpio
                Description     : Use the Linux sysfs interface to bitbang GPIO lines
                Pin assignment  : /sys/class/gpio/gpio{n}
                  RESET   =  0
                  SCK     =  11
                  SDO     =  10
                  SDI     =  9

11110avrdude_pr1231: AVR device initialized and ready to accept instructions
011011011avrdude_pr1231: device signature = 0x1e950f (probably m328p)
1
avrdude_pr1231 done.  Thank you.
```

2022-12-26 13:03 UTC, mcuee commented
@stefanrueger 

It does seem to be caused by this PR. git main is okay.

```
pi@raspberrypi:~/build/avr/avrdude_bin $ ./avrdude_git -C avrdude_gpio_25.conf -c linuxgpio -p m328p

avrdude_git: AVR device initialized and ready to accept instructions
avrdude_git: device signature = 0x1e950f (probably m328p)

avrdude_git done.  Thank you.

pi@raspberrypi:~/build/avr/avrdude_bin $ ./avrdude_pr1231 -C avrdude_gpio_25.conf -c linuxgpio -p m328p

11110avrdude_pr1231: AVR device initialized and ready to accept instructions
011011011avrdude_pr1231: device signature = 0x1e950f (probably m328p)
1
avrdude_pr1231 done.  Thank you.


```

2022-12-26 13:19 UTC, mcuee commented
@stefanrueger 

And it is not caused by your further commits, as [the first commit](https://github.com/wijnen/avrdude/commit/c4c5d10a57c348e8fbf8d3c8761a3af474747b01) by @wijnen already causes this problem.
```
pi@raspberrypi:~/build/avr/avrdude_bin $ ./avrdude_pr1231_org -C avrdude_gpio_25.conf -c linuxgpio -p m328p -vvvv
sys_config = avrdude_gpio_25.conf
sys_config_found = false


avrdude_pr1231_org: Version 7.0-20221219 (c4c5d10)
                    Copyright the AVRDUDE authors;
                    see https://github.com/avrdudes/avrdude/blob/main/AUTHORS

                    System wide configuration file is /home/pi/build/avr/avrdude_bin/avrdude_gpio_25.conf
                    User configuration file is /home/pi/.avrduderc
                    User configuration file does not exist or is not a regular file, skipping

                    Using Port                    : /dev/parport0
                    Using Programmer              : linuxgpio
                    AVR Part                      : ATmega328P
                    Chip Erase delay              : 9000 us
                    PAGEL                         : PD7
                    BS2                           : PC2
                    RESET disposition             : possible i/o
                    RETRY pulse                   : SCK
                    Serial program mode           : yes
                    Parallel program mode         : yes
                    Timeout                       : 200
                    StabDelay                     : 100
                    CmdexeDelay                   : 25
                    SyncLoops                     : 32
                    PollIndex                     : 3
                    PollValue                     : 0x53
                    Memory Detail                 :

                                                      Block Poll               Page                       Polled
                      Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
                      ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
                      eeprom                 65    20     4    0 no       1024    4      0  3600  3600 0xff 0xff
                                                      Block Poll               Page                       Polled
                      Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
                      ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
                      flash                  65     6   128    0 yes     32768  128    256  4500  4500 0xff 0xff
                                                      Block Poll               Page                       Polled
                      Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
                      ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
                      lfuse                   0     0     0    0 no          1    1      0  4500  4500 0x00 0x00
                                                      Block Poll               Page                       Polled
                      Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
                      ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
                      hfuse                   0     0     0    0 no          1    1      0  4500  4500 0x00 0x00
                                                      Block Poll               Page                       Polled
                      Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
                      ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
                      efuse                   0     0     0    0 no          1    1      0  4500  4500 0x00 0x00
                                                      Block Poll               Page                       Polled
                      Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
                      ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
                      lock                    0     0     0    0 no          1    1      0  4500  4500 0x00 0x00
                                                      Block Poll               Page                       Polled
                      Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
                      ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
                      signature               0     0     0    0 no          3    1      0     0     0 0x00 0x00
                                                      Block Poll               Page                       Polled
                      Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
                      ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
                      calibration             0     0     0    0 no          1    1      0     0     0 0x00 0x00

                    Programmer Type : linuxgpio
                    Description     : Use the Linux sysfs interface to bitbang GPIO lines
                    Pin assignment  : /sys/class/gpio/gpio{n}
                      RESET   =  25
                      SCK     =  11
                      SDO     =  10
                      SDI     =  9

0000avrdude_pr1231_org: calibrating delay loop ... calibrated to 249 cycles per us
bitbang_cmd(): [ AC 53 00 00 ] [ 00 00 53 00 ]
1avrdude_pr1231_org: AVR device initialized and ready to accept instructions

Reading |                                                    | 0% 0.00 s 10bitbang_cmd(): [ 30 00 00 00 ] [ 00 30 00 1E ]
010bitbang_cmd(): [ 30 00 01 00 ] [ 00 30 00 95 ]
Reading | #################                                  | 33% 0.00 s 10bitbang_cmd(): [ 30 00 02 00 ] [ 00 30 00 0F ]
Reading | ################################################## | 100% 0.00 s 

avrdude_pr1231_org: device signature = 0x1e950f (probably m328p)
0
avrdude_pr1231_org done.  Thank you.

```

2022-12-26 13:42 UTC, mcuee commented
I tried to debug this one, but it seems to me the change to `linuxgpio.c` may not be the problem.

```
pi@raspberrypi:~/build/avr/avrdude_pr1231 $ git diff
diff --git a/src/linuxgpio.c b/src/linuxgpio.c
index f63a95f..3d76277 100644
--- a/src/linuxgpio.c
+++ b/src/linuxgpio.c
@@ -252,7 +252,11 @@ static int linuxgpio_open(PROGRAMMER *pgm, const char *port) {
     linuxgpio_fds[i] = -1;
   //Avrdude assumes that if a pin number is -1 it means not used/available
   for (i=0; i<N_PINS; i++) {
-    if (pgm->pinno[i] <= PIN_MAX) {
+    if ( (pgm->pinno[i] & PIN_MASK) != NO_PIN ||
+         i == PIN_AVR_RESET ||
+         i == PIN_AVR_SCK   ||
+         i == PIN_AVR_SDO   ||
+         i == PIN_AVR_SDI ) {
         pin = pgm->pinno[i] & PIN_MASK;
         if ((r=linuxgpio_export(pin)) < 0) {
             pmsg_ext_error("cannot export GPIO %d, already exported/busy?: %s",

pi@raspberrypi:~/build/avr/avrdude_bin $ ./avrdude_pr1231_mod1 -C avrdude_gpio_25.conf -c linuxgpio -p m328p -vvvv
sys_config = avrdude_gpio_25.conf
sys_config_found = false


avrdude_pr1231_mod1: Version 7.0-20221223 (184c62c)
                     Copyright the AVRDUDE authors;
                     see https://github.com/avrdudes/avrdude/blob/main/AUTHORS

                     System wide configuration file is /home/pi/build/avr/avrdude_bin/avrdude_gpio_25.conf
                     User configuration file is /home/pi/.avrduderc
                     User configuration file does not exist or is not a regular file, skipping

                     Using Port                    : /dev/parport0
                     Using Programmer              : linuxgpio
                     AVR Part                      : ATmega328P
                     Chip Erase delay              : 9000 us
                     PAGEL                         : PD7
                     BS2                           : PC2
                     RESET disposition             : possible i/o
                     RETRY pulse                   : SCK
                     Serial program mode           : yes
                     Parallel program mode         : yes
                     Timeout                       : 200
                     StabDelay                     : 100
                     CmdexeDelay                   : 25
                     SyncLoops                     : 32
                     PollIndex                     : 3
                     PollValue                     : 0x53
                     Memory Detail                 :

                                                       Block Poll               Page                       Polled
                       Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
                       ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
                       eeprom                 65    20     4    0 no       1024    4      0  3600  3600 0xff 0xff
                                                       Block Poll               Page                       Polled
                       Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
                       ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
                       flash                  65     6   128    0 yes     32768  128    256  4500  4500 0xff 0xff
                                                       Block Poll               Page                       Polled
                       Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
                       ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
                       lfuse                   0     0     0    0 no          1    1      0  4500  4500 0x00 0x00
                                                       Block Poll               Page                       Polled
                       Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
                       ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
                       hfuse                   0     0     0    0 no          1    1      0  4500  4500 0x00 0x00
                                                       Block Poll               Page                       Polled
                       Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
                       ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
                       efuse                   0     0     0    0 no          1    1      0  4500  4500 0x00 0x00
                                                       Block Poll               Page                       Polled
                       Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
                       ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
                       lock                    0     0     0    0 no          1    1      0  4500  4500 0x00 0x00
                                                       Block Poll               Page                       Polled
                       Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
                       ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
                       signature               0     0     0    0 no          3    1      0     0     0 0x00 0x00
                                                       Block Poll               Page                       Polled
                       Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
                       ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
                       calibration             0     0     0    0 no          1    1      0     0     0 0x00 0x00

                     Programmer Type : linuxgpio
                     Description     : Use the Linux sysfs interface to bitbang GPIO lines
                     Pin assignment  : /sys/class/gpio/gpio{n}
                       RESET   =  25
                       SCK     =  11
                       SDO     =  10
                       SDI     =  9

1111avrdude_pr1231_mod1: calibrating delay loop ... calibrated to 222 cycles per us
bitbang_cmd(): [ AC 53 00 00 ] [ 00 00 53 00 ]
0avrdude_pr1231_mod1: AVR device initialized and ready to accept instructions

Reading |                                                    | 0% 0.00 s 01bitbang_cmd(): [ 30 00 00 00 ] [ 00 30 00 1E ]
101bitbang_cmd(): [ 30 00 01 00 ] [ 00 30 00 95 ]
Reading | #################                                  | 33% 0.00 s 01bitbang_cmd(): [ 30 00 02 00 ] [ 00 30 00 0F ]
Reading | ################################################## | 100% 0.00 s 

avrdude_pr1231_mod1: device signature = 0x1e950f (probably m328p)
1
avrdude_pr1231_mod1 done.  Thank you.
```

2022-12-26 19:08 UTC, stefanrueger commented
> change to linuxgpio.c is not logically the same as the original code

Well spotted @mcuee, I missed that. I have pushed a commit that considers PIN_MASK for pin validity. As to the  additional ` || i == PIN_AVR_RESET ||  i == PIN_AVR_SCK   ||  i == PIN_AVR_SDO   || i == PIN_AVR_SDI` test I prefer @wijnen's decision to leave this away - as this could only change if the pin assignment for any of these pins was invalid...

Pushed a commit

2022-12-27 00:13 UTC, mcuee commented
@stefanrueger 

I took the liberty to merge PR #1239.
For this PR, please merge git main to triger the new github action. Thanks.

2022-12-27 00:33 UTC, mcuee commented
> > change to linuxgpio.c is not logically the same as the original code
> 
> Well spotted @mcuee, I missed that. I have pushed a commit that considers PIN_MASK for pin validity. As to the additional ` || i == PIN_AVR_RESET || i == PIN_AVR_SCK || i == PIN_AVR_SDO || i == PIN_AVR_SDI` test I prefer @wijnen's decision to leave this away - as this could only change if the pin assignment for any of these pins was invalid...
> 
> Pushed a commit

@stefanrueger 

Unfortunately the issue is still there.

```

pi@raspberrypi:~/build/avr/avrdude_bin $ ./avrdude_pr1231v1
Usage: avrdude_pr1231v1 [options]
Options:
  -p <partno>                Specify AVR device
  -b <baudrate>              Override RS-232 baud rate
  -B <bitclock>              Specify bit clock period (us)
  -C <config-file>           Specify location of configuration file
  -c <programmer>            Specify programmer type
  -A                         Disable trailing-0xff removal from file and AVR read
  -D                         Disable auto erase for flash memory; implies -A
  -i <delay>                 ISP Clock Delay [in microseconds]
  -P <port>                  Specify connection port
  -F                         Override invalid signature or initialisation check
  -e                         Perform a chip erase
  -O                         Perform RC oscillator calibration (see AVR053)
  -U <memtype>:r|w|v:<filename>[:format]
                             Memory operation specification
                             Multiple -U options are allowed, each request
                             is performed in the order specified
  -n                         Do not write anything to the device
  -V                         Do not verify
  -t                         Enter terminal mode
  -E <exitspec>[,<exitspec>] List programmer exit specifications
  -x <extended_param>        Pass <extended_param> to programmer
  -v                         Verbose output; -v -v for more
  -q                         Quell progress output; -q -q for less
  -l logfile                 Use logfile rather than stderr for diagnostics
  -?                         Display this usage

avrdude version 7.0-20221226 (32cf5f1), URL: <https://github.com/avrdudes/avrdude>

pi@raspberrypi:~/build/avr/avrdude_bin $ ./avrdude_pr1231v1 -C avrdude_gpio_25.conf -c linuxgpio -p m328p

11110avrdude_pr1231v1: AVR device initialized and ready to accept instructions
011011011avrdude_pr1231v1: device signature = 0x1e950f (probably m328p)
1
avrdude_pr1231v1 done.  Thank you.

pi@raspberrypi:~/build/avr/avrdude_bin $ ./avrdude -C avrdude_gpio_25.conf -c linuxgpio -p m328p

avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1e950f (probably m328p)

avrdude done.  Thank you.

```

2022-12-27 12:03 UTC, stefanrueger commented
Thanks, I'll have a look later, but it doesn't look like an easy thing to find.

> nano build.sh

@mcuee: Is the editing of build.sh related to this [comment](https://github.com/avrdudes/avrdude/issues/1107#issuecomment-1265873339)? If so, is there a good reason to not change `ON`/`OFF` to `1`/`0` this in git-main before releasing v7.1?

2022-12-27 12:34 UTC, mcuee commented
> > nano build.sh
> 
> @mcuee: Is the editing of build.sh related to this [comment](https://github.com/avrdudes/avrdude/issues/1107#issuecomment-1265873339)? If so, is there a good reason to not change `ON`/`OFF` to `1`/`0` in git-main before releasing v7.1?

Yes. I have merged  https://github.com/avrdudes/avrdude/pull/1240 into git main to address #1107.

2022-12-31 14:56 UTC, stefanrueger commented
I don't have a clear view where the bitstreams come from. One of the few places that look like they could emit bitstreams is linuxgpio_setpin(). The code does not particularly guard against values outside the arrays that are used.

I reviewed again, and added sanity checks, in particular array index checks. 

I don't think this solves the problem, and if it does, I still think we should be clear where the illicit calls come from. I checked all use of pgm->setpin(), particularly in `bitbang.c` and `linusgpio.c`

2022-12-31 15:19 UTC, stefanrueger commented
There is one peculiarity in the existing code:
  - AVRDUDE knows about pins defined [here](https://github.com/avrdudes/avrdude/blob/0f956e90eb66e0ba7a4fecdd59e6fab31f346963/src/libavrdude.h#L409-L421)
  - Notice that this enum starts counting from 1: `PPI_AVR_VCC = 1`
  - Loops over the pins usually start from 0

I have changed that in linuxgpio.c, but not in other places.

@mcuee Would be interesting to see whether linuxspi, bitbang, linuxgpio still works :wink:

2023-01-01 01:16 UTC, mcuee commented
> @mcuee Would be interesting to see whether linuxspi, bitbang, linuxgpio still works 😉

Great, now linuxgpio seems to work fine. I think I do not have a working programmer using bitbang now.

``
pi@raspberrypi:~/build/avr/avrdude_bin $ ./avrdude_pr1231v2 -C avrdude_gpio_25.conf -c linuxgpio
 -P GPIO  -p m328p

avrdude_pr1231v2: AVR device initialized and ready to accept instructions
avrdude_pr1231v2: device signature = 0x1e950f (probably m328p)

avrdude_pr1231v2 done.  Thank you.

```

2023-01-01 03:58 UTC, mcuee commented
@stefanrueger 

I am not so sure if the following is a good test for `bitbang`. I think `ft245r.c` does use `bitbang.h`.

```
PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1231v2  -c arduino-ft232r -p m328p -U .\hex\Blink.ino.with_bootloader.standard.hex -v

avrdude_pr1231v2: Version 7.0-20221231 (eae16c8)
                  Copyright the AVRDUDE authors;
                  see https://github.com/avrdudes/avrdude/blob/main/AUTHORS

                  System wide configuration file is C:\work\avr\avrdude_test\avrdude_bin\avrdude.conf

                  Using Port                    : usb
                  Using Programmer              : arduino-ft232r
avrdude_pr1231v2: ft245r_open(): no device identifier in portname, using default
avrdude_pr1231v2: input file .\hex\Blink.ino.with_bootloader.standard.hex auto detected as Intel Hex
                  AVR Part                      : ATmega328P
                  Chip Erase delay              : 9000 us
                  PAGEL                         : PD7
                  BS2                           : PC2
                  RESET disposition             : possible i/o
                  RETRY pulse                   : SCK
                  Serial program mode           : yes
                  Parallel program mode         : yes
                  Timeout                       : 200
                  StabDelay                     : 100
                  CmdexeDelay                   : 25
                  SyncLoops                     : 32
                  PollIndex                     : 3
                  PollValue                     : 0x53
                  Memory Detail                 :

                                                    Block Poll               Page                       Polled
                    Memory Type Alias    Mode Delay Size  Indx Paged  Size   Size #Pages MinW  MaxW   ReadBack
                    ----------- -------- ---- ----- ----- ---- ------ ------ ---- ------ ----- ----- ---------
                    eeprom                 65    20     4    0 no       1024    4      0  3600  3600 0xff 0xff
                    flash                  65     6   128    0 yes     32768  128    256  4500  4500 0xff 0xff
                    lfuse                   0     0     0    0 no          1    1      0  4500  4500 0x00 0x00
                    hfuse                   0     0     0    0 no          1    1      0  4500  4500 0x00 0x00
                    efuse                   0     0     0    0 no          1    1      0  4500  4500 0x00 0x00
                    lock                    0     0     0    0 no          1    1      0  4500  4500 0x00 0x00
                    signature               0     0     0    0 no          3    1      0     0     0 0x00 0x00
                    calibration             0     0     0    0 no          1    1      0     0     0 0x00 0x00

                  Programmer Type : ftdi_syncbb
                  Description     : Arduino: FT232R connected to ISP
                  Pin assignment  : 0..7 = DBUS0..7
                    VCC     =  (not used)
                    BUFF    =  (not used)
                    RESET   =  7
                    SCK     =  5
                    SDO     =  6
                    SDI     =  3
                    ERR LED =  (not used)
                    RDY LED =  (not used)
                    PGM LED =  (not used)
                    VFY LED =  (not used)

avrdude_pr1231v2: AVR device initialized and ready to accept instructions
avrdude_pr1231v2: device signature = 0x1e950f (probably m328p)
avrdude_pr1231v2: Note: flash memory has been specified, an erase cycle will be performed.
                  To disable this feature, specify the -D option.
avrdude_pr1231v2: erasing chip
avrdude_pr1231v2: reading input file .\hex\Blink.ino.with_bootloader.standard.hex for flash
                  with 1426 bytes in 3 sections within [0, 0x7fff]
                  using 12 pages and 110 pad bytes
avrdude_pr1231v2: writing 1426 bytes flash ...

Writing | ################################################## | 100% 0.86 s

avrdude_pr1231v2: 1426 bytes of flash written
avrdude_pr1231v2: verifying flash memory against .\hex\Blink.ino.with_bootloader.standard.hex

Reading | ################################################## | 100% 0.61 s

avrdude_pr1231v2: 1426 bytes of flash verified

avrdude_pr1231v2 done.  Thank you.
```

2023-01-01 15:27 UTC, stefanrueger commented
| I think ft245r.c does use bitbang.h

As does [linuxgpio.c](https://github.com/avrdudes/avrdude/blob/b2c03f5d4094335544e2becaba157fa4689006a6/src/linuxgpio.c#L348-L374). Notice that `pgm->cmd` is provided by bitbang?

2023-01-01 15:28 UTC, stefanrueger commented
OK, looks like this can be merged before the 7.1 release, but I leave the final decision to @dl8dtl.

2023-01-02 14:23 UTC, merged