Add serial port discovery
avrdudes/avrdude pull request #1498
Opened 2023-08-31 22:28 UTC by MCUdude

This PR adds serial port discovery functionality using libserialport. Please test and review!

```
$ avrdude -curclock -patmega169 -P ch340
avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1e9405 (probably m169)

avrdude done.  Thank you.
```

It is also possible to specify a serial number like this: `-P ft232r:A50285BI`, using USB VID/PID like so: `-P 0x0403:0x6002`, or using USB VID/PID/SN like so: `-P 0x0403:0x6002:A50285BI`

For some reason, I'm getting a linker error when building using make. Perhaps @dl8dtl knows what causes this?

```
make
/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in .
  CC       avrdude-main.o
  CC       libavrdude_a-serialadapter.o
  AR       libavrdude.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libavrdude.a(libavrdude_a-confwin.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libavrdude.a(libavrdude_a-ppi.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libavrdude.a(libavrdude_a-ppiwin.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libavrdude.a(libavrdude_a-serbb_win32.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libavrdude.a(libavrdude_a-ser_win32.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libavrdude.a(libavrdude_a-confwin.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libavrdude.a(libavrdude_a-ppi.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libavrdude.a(libavrdude_a-ppiwin.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libavrdude.a(libavrdude_a-serbb_win32.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libavrdude.a(libavrdude_a-ser_win32.o) has no symbols
  CCLD     avrdude
ld: warning: directory not found for option '-FCoreFoundation'
Undefined symbols for architecture x86_64:
  "_sp_free_port_list", referenced from:
      _find_serialport_adapter in libavrdude.a(libavrdude_a-serialadapter.o)
      _find_serialport_vid_pid in libavrdude.a(libavrdude_a-serialadapter.o)
  "_sp_get_port_name", referenced from:
      _find_serialport_adapter in libavrdude.a(libavrdude_a-serialadapter.o)
      _find_serialport_vid_pid in libavrdude.a(libavrdude_a-serialadapter.o)
  "_sp_get_port_usb_serial", referenced from:
      _find_serialport_adapter in libavrdude.a(libavrdude_a-serialadapter.o)
      _find_serialport_vid_pid in libavrdude.a(libavrdude_a-serialadapter.o)
  "_sp_get_port_usb_vid_pid", referenced from:
      _find_serialport_adapter in libavrdude.a(libavrdude_a-serialadapter.o)
      _find_serialport_vid_pid in libavrdude.a(libavrdude_a-serialadapter.o)
  "_sp_list_ports", referenced from:
      _find_serialport_adapter in libavrdude.a(libavrdude_a-serialadapter.o)
      _find_serialport_vid_pid in libavrdude.a(libavrdude_a-serialadapter.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [avrdude] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2

2023-08-31 23:19 UTC, mcuee commented
@MCUdude 
I think you have to add libserail port detection to `configure.ac`.
https://github.com/avrdudes/avrdude/blob/main/src/configure.ac

2023-08-31 23:36 UTC, mcuee commented
There are a few warnings when building using MinGW64.
https://github.com/avrdudes/avrdude/actions/runs/6043108677/job/16399525881?pr=1498

Same for my local build.
```
[65/71] Building C object src/CMakeFiles/avrdude.dir/main.c.obj
C:/work/avr/avrdude_test/avrdude_hans/src/main.c: In function 'main':
C:/work/avr/avrdude_test/avrdude_hans/src/main.c:1184:11: warning: the comparison will always evaluate as 'true' for the address of 'port_tok' will never be NULL [-Waddress]
 1184 |       if (port_tok[1] && port_tok[1][0])
      |           ^~~~~~~~
C:/work/avr/avrdude_test/avrdude_hans/src/main.c:1168:8: note: 'port_tok' declared here
 1168 |   char port_tok[3][256];
      |        ^~~~~~~~
C:/work/avr/avrdude_test/avrdude_hans/src/main.c:1191:9: warning: the comparison will always evaluate as 'true' for the address of 'port_tok' will never be NULL [-Waddress]
 1191 |     if (port_tok[1] && port_tok[1][0])
      |         ^~~~~~~~
C:/work/avr/avrdude_test/avrdude_hans/src/main.c:1168:8: note: 'port_tok' declared here
 1168 |   char port_tok[3][256];
      |        ^~~~~~~~
C:/work/avr/avrdude_test/avrdude_hans/src/main.c:1201:13: warning: the comparison will always evaluate as 'true' for the address of 'port_tok' will never be NULL [-Waddress]
 1201 |         if (port_tok[2] && port_tok[2][0])
      |             ^~~~~~~~
C:/work/avr/avrdude_test/avrdude_hans/src/main.c:1168:8: note: 'port_tok' declared here
 1168 |   char port_tok[3][256];
      |        ^~~~~~~~
[71/71] Linking C executable src\avrdude.exe

Build succeeded.
```

2023-08-31 23:40 UTC, mcuee commented
@MCUdude 

github action script needs to be added as well to install `libserialport` for each OS. If not, right now the builds are without libserialport.
https://github.com/avrdudes/avrdude/blob/main/.github/workflows/build.yml

I am not so sure how to do that for MSVC build though. Probably @mariusgreuel can help.

2023-09-01 06:18 UTC, MCUdude commented
> I think you have to add libserial port detection to configure.ac.

True, but I don't know how/where... @dl8dtl?

> There are a few warnings when building using MinGW64.

Thanks for the heads-up! I've pushed a fix for this.

> github action script needs to be added as well to install libserialport for each OS. If not, right now the builds are without libserialport.

The question is if we want the CI to build Avrdude with or without libserialport support. Avrdude _should_ work perfectly fine without as well, so it might be a good test to _not_ have libserialport installed? I don't know. @mariusgreuel probably has something to say about this.

But apart from this, does the PR work for you @mcuee?

2023-09-01 09:13 UTC, mcuee commented
> But apart from this, does the PR work for you @mcuee?

I will carry out the tests over the weekend.

2023-09-01 09:16 UTC, mcuee commented
> The question is if we want the CI to build Avrdude with or without libserialport support. Avrdude should work perfectly fine without as well, so it might be a good test to not have libserialport installed? I don't know. @mariusgreuel probably has something to say about this.

I think we can at least build avrdude with libserialport support with Linux, macOS and MinGW where it is easier to add support. 

BTW, since we only provide official Windows binary using MSVC build where we have to wait for @mariusgreuel or others to help support, the above change will not change status quo.

2023-09-01 11:50 UTC, stefanrueger commented
Started reviewing. There are serious problems with port assignment. Here a [patch 0001-Fix-port-assignment](https://github.com/avrdudes/avrdude/files/12497548/0001-Fix-port-assignment.zip):
 - Ensure port is always set by cfg_strdup(), so it can be free'd
 - Fix possible buffer overrun when tokenising port
 - Free and reassign port string rather than copying over it as it has unknown allocated length
 - Warn if sp_get_port_name() returns NULL and return -1
 - Remove superfluous continue

2023-09-01 12:07 UTC, stefanrueger commented on src/main.c
> +  } else if (is_programmer(ser)) {
This branch is not helpful and can be deleted. I could have a symbolic link
```
$ ln -s /dev/ttyUSB0 urclock
```
and regularly program using `-P urclock`. This branch would all of a sudden make this impossible.

2023-09-01 12:15 UTC, stefanrueger commented on src/main.c
> +        exit(1);
I would not exit here

2023-09-01 12:17 UTC, stefanrueger commented on src/main.c
> +      pmsg_error("invalid serial adapter %s with serial number %s specified\n", seradapter, port_tok[1]);
This error (and others) could be demoted to warnings, as `pgm->open()` could conceivably still work (see other comments).

2023-09-01 12:39 UTC, MCUdude commented
Thank you for the feedback! I've applied the patch you provided and the other suggestions as well. The code is very much "experimental", and is a result of me fighting segfaults and fooling around an entire evening. The functionality is there, but it absolutely needs a critical review and some work.

>  If I understand your PR correctly it would silently be uploaded to one of the two plugged in ch340 boards

Yes, that's correct. Ideally, it should loop through the port list to make sure that the user-specified USB to serial adapter is unique, and stop the upload process if there is a chance that the incorrect serial port may be chosen.

If you have suggestions on how something like this could be implemented, feel free to submit a patch or explain what you'd do. I'm not available this evening (it's my wife's birthday today), but I will be on Saturday and Sunday evening.

2023-09-01 23:10 UTC, stefanrueger commented
One idea may be dreaming up a general complex use case. For example, a user has 7 boards plugged into the host: two original FT232R with a proper serial number, two cheap clones with identical serial numbers, a direct USART connector, a CH340 serial adapter (which don't have serial numbers) and a new connector CH911 that isn't known to `avrdude.conf`
 - ft232r:A600K207683 `->` /dev/ttyUSB1
 - ft232r:A600K207684 `->` /dev/ttyUSB7
 - ft232r:cheapo `->` /dev/ttyUSB9
 - ft232r:cheapo `->` /dev/ttyUSB3
 - /dev/ttyAMA0
 - ch340 `->` /dev/ttyUSB4
 - ch911 `->` /dev/ttyUSB8

Here a few suggestions that the code could consider
 - Only deploy the serial port discovery for `-c` programmers where the `connection_type` is serial
 - Check whether a given -P serialadapter string *uniquely* identifies a port, only then overwrite the `port` string
 - If the serialadapter code identifies multiple possible ports, show the user all possible *unique* alternatives (and do *not* overwrite the `port` string); for example, if the user requests `-P ft232r` then the output could be sth like
   ```
    avrdude warning: -P ft232r is not unique; consider one of the below
     -P /dev/ttyUSB1 or -P ft232r:A600K207683
     -P /dev/ttyUSB3 (via ft232r serial adapter)
     -P /dev/ttyUSB7 or -P ft232r:A600K207684
     -P /dev/ttyUSB9 (via ft232r serial adapter)
   ```
   Note that `-P ft232r:cheapo` isn't shown as it wouldn't result in a unique port string.
 - If `-P string` is not found as serial adapter, let `pgm->open()` try (could be a valid serial port or a symbolic link to one)
 - As always, the most important question is *How would users know* of AVRDUDE's new serial port discovery super power? They might not even know what a serial adapter is, nor that they could have serial number, nor that they can be specified instead of the serial port, nor what the syntax is for doing so. Sooooo, in above scenario when `pgm->open()` does fail *and* the programmer's `connection_type` is serial and there wasn't already a list of multiple possible ports given (see above) it would be *fabulous* to list possible connected devices:
   ```
   $ avrdude -P /dev/ttyUSB2
   avrdude error: unable to open programmer urclock on port /dev/ttyUSB2
   Possible candidate serial ports are:
     -P /dev/ttyUSB1 or -P ft232r:A600K207683
     -P /dev/ttyUSB3 (via ft232r serial adapter)
     -P /dev/ttyUSB4 or -P ch340
     -P /dev/ttyUSB7 or -P ft232r:A600K207684
     -P /dev/ttyUSB8 or -P usb:C0CA:C01A (serial adapter unknown to avrdude.conf)
     -P /dev/ttyUSB9 (via ft232r serial adapter)
   Note that above ports may not necessarily be connected to a target board or an AVR programmer.
   Also note there may be other direct serial ports not listed above.
   ```
   Of course, if serial port discovery yields only one candidate then the grammar should be singular along the lines of:
   ```
   $ avrdude -P /dev/ttyUSB2
   avrdude error: unable to open programmer urclock on port /dev/ttyUSB2
   A possible candidate serial port is -P /dev/ttyUSB4 (same as -P ch340) but
   note it may not be connected to a target board or an AVR programmer and also
   note there may be other direct serial ports.
   ```
 - Implement `-P usb:VID:PID[:serial]` for serial adapters not in `avrdude.conf` :)
 - Trailing serial numbers should be sufficient if unique on the host (as is the case for USB connections): `-P ft232r:83`
 - Seeing as we aspire to publishing libavrdude may I suggest slightly clearer function names:
   + find_serialport_adapter() `->` setport_from_serialadapter()
   + find_serialport_vid_pid() `->` setport_from_vid_pid()

I don't know how to turn Jörg's other [suggestion](https://github.com/avrdudes/avrdude/pull/1497#issuecomment-1697935286) into code as it only affects direct USB connections (`connection_type = usb`) which would remain unchanged but his suggestion of generic `usb` serial adapter specification just like for direct usb connections is already in above list, as is the trailing serial number.

2023-09-02 01:26 UTC, mcuee commented
This PR seems to work well under Windows.
```
$ ./port_finder/port_finder.exe ch340
Found port:
id:     ch340
desc:   USB-SERIAL CH340 (COM41)
port:   COM41
serno:

$ ./avrdude_pr1498v1 -C ./avrdude_pr1498v1.conf -c wiring -p m2560 -P COM41
avrdude_pr1498v1: AVR device initialized and ready to accept instructions
avrdude_pr1498v1: device signature = 0x1e9801 (probably m2560)

avrdude_pr1498v1 done.  Thank you.

$ ./avrdude_pr1498v1 -C ./avrdude_pr1498v1.conf -c wiring -p m2560 -P ch340
avrdude_pr1498v1: AVR device initialized and ready to accept instructions
avrdude_pr1498v1: device signature = 0x1e9801 (probably m2560)

avrdude_pr1498v1 done.  Thank you.

$ ./avrdude_pr1498v1 -C ./avrdude_pr1498v1.conf -c wiring -p m2560 -P 0x1a86:0x7523
avrdude_pr1498v1: AVR device initialized and ready to accept instructions
avrdude_pr1498v1: device signature = 0x1e9801 (probably m2560)

avrdude_pr1498v1 done.  Thank you.
```

2023-09-02 01:33 UTC, mcuee commented
Another example with Arduino Uno clone with ATmega16U2 USB CDC-ACM serial port.

@MCUdude I am not so sure how to specify `programmer ID` in this case.
```
$ ./port_finder/port_finder.exe
Missing programmer ID, e.g ch340

$ ./avrdude_pr1498v1 -C ./avrdude_pr1498v1.conf -c urclock -p m328p -P COM40
avrdude_pr1498v1: AVR device initialized and ready to accept instructions
avrdude_pr1498v1: device signature = 0x1e950f (probably m328p)

avrdude_pr1498v1 done.  Thank you.


$ ./avrdude_pr1498v1 -C ./avrdude_pr1498v1.conf -c urclock -p m328p -P 0x2341:0x0043
avrdude_pr1498v1: AVR device initialized and ready to accept instructions
avrdude_pr1498v1: device signature = 0x1e950f (probably m328p)

avrdude_pr1498v1 done.  Thank you.
```

2023-09-02 19:48 UTC, MCUdude commented
Thanks for the valuable input @stefanrueger! Now Avrdude requires the port to be unique, and it will print the alternative options if not. The code works but needs another set of eyes to make sure it's as efficient as possible. There are a bunch of for loops in there; maybe a clever mind can simply the code a bit.

One thing I didn't figure out is how to properly deal with the `serports` struct. The idea is to use libserialport to loop through all serial ports and store the useful information in an array of `serports` structs. However, the `sernum` and `port` strings are fixed sizes, and the maximum number of serial ports is 32.

It would be great if you could suggest how this could be dealt with dynamically.

2023-09-02 22:51 UTC, stefanrueger commented
Cool... progress!

> the sernum and port strings are fixed sizes

Can do but then it's a no-no to `strcpy()` strings of unknown length into the fixed space. Why not declare them `char *` and assign via malloc'd space? `char *port = cfg_strdup(__func__, xxx);` Can be free'd when deconstructing the storage. 

> maximum number of serial ports is 32

The code could first count how many there are and then allocate the space?
```
int n;
for (n = 0; port_list[n]; n++)
  continue;

struct serports *sp = cfg_malloc(__func__, n*sizeof*sp);

for(int i = 0; i < n; i++) {
  // ... set prt
  sp[i].sernum = cfg_strdup(__func__, sp_get_port_usb_serial(prt));
  sp[i].port = cfg_strdup(__func__, sp_get_port_name(prt));
}
```


When you don't need the array deconstruct via
```
for(int i = 0; i < n; i++) {
  free(sp[i].sernum);
  free(sp[i].port);
}
free(sp);
```

2023-09-03 17:44 UTC, MCUdude commented
I've pushed a few commits that resolves a few issues.

> As always, the most important question is How would users know of AVRDUDE's new serial port discovery super power? They might not even know what a serial adapter is, nor that they could have serial number, nor that they can be specified instead of the serial port, nor what the syntax is for doing so. Sooooo, in above scenario when pgm->open() does fail and the programmer's connection_type is serial and there wasn't already a list of multiple possible ports given (see above) it would be fabulous to list possible connected devices:

```
$ avrdude -P /dev/ttyUSB2
avrdude error: unable to open programmer urclock on port /dev/ttyUSB2
Possible candidate serial ports are:
  -P /dev/ttyUSB1 or -P ft232r:A600K207683
  -P /dev/ttyUSB3 (via ft232r serial adapter)
  -P /dev/ttyUSB4 or -P ch340
  -P /dev/ttyUSB7 or -P ft232r:A600K207684
  -P /dev/ttyUSB8 or -P usb:C0CA:C01A (serial adapter unknown to avrdude.conf)
  -P /dev/ttyUSB9 (via ft232r serial adapter)
Note that above ports may not necessarily be connected to a target board or an AVR programmer.
Also note there may be other direct serial ports not listed above.
```

@stefanrueger I'm struggling to figure out how to do this. Printing the port and serial number is the easy part. However, using the USB VID/PID to figure out which serialadapter string (`ft232r` or `ch340` for instance) to print based on the match in avrdude.conf is the hard part. Is it OK if I create a function that prints the path and SN, and maybe you can help me figure out how to do some sort of reverse lookup in avrdude.conf?

2023-09-03 18:17 UTC, MCUdude commented
@stefanrueger I've now added `print_available_serialports()` which prints the following when a non-existing port is passed:

```
$ ./build_darwin/src/avrdude -curclock -patmega169 -P /dev/not_a_port
avrdude OS error: cannot open port /dev/not_a_port: No such file or directory
avrdude error: unable to open programmer urclock on port /dev/notaport
Possible candidate serial ports are:
-P /dev/cu.Bluetooth-Incoming-Port
-P /dev/cu.usbserial-1420 or -P 1a86:7523
-P /dev/cu.usbserial-AH00M3HQ or -P 0403:6001:AH00M3HQ
Note that above ports may not necessarily be connected to a target board or an AVR programmer.
Also note there may be other direct serial ports not listed above.

avrdude done.  Thank you.

```

Would be great if you could look into how to turn `1a86:7523` into `ch340`, and `0403:6001:AH00M3HQ` into `ft232r:AH00M3HQ`

2023-09-03 20:01 UTC, stefanrueger commented
@MCUdude Thanks for all the commits and commitment! It'll take a while for me to do a proper review (vvv busy), but I am sure that you'll be able to play with your code and test functionality in the meantime as I predict will @mcuee. I am also sure that you don't need my (or anyone else's) help to figure out the reverse problem (given vid and pid, which AVRDUDE serial adapters uniquely specify that combo).

I happened to note that Jörg talked about *trailing* serial number but the new serial code matches the *start* of the serial number. I imagine (but do not know) that serial numbers are more likely to vary in the end section than the beginning section. Would be cool to converge both usb notations, the existing `-P usb:...` for devices directly connected to USB and the new one `-P ...` for serial adapters.  Speaking of that I would *not* introduce `-P <vid>:<pid>[:<serialnumber>]`. I would only use `-P usb:<vid>:<pid>[:<serialnumber>]`. Otherwise this PR might call for the desire to implement `-P <vid>:<pid>[:<serialnumber>]` for the USB devices too (and as they are implemented per programmer that's a lot of work). And we'd need to document a lot more ;)

But yes, this *really* currently looks like an exciting new super power for AVRDUDE, and thank you for the idea in the first place and for implementing that.

2023-09-03 20:28 UTC, MCUdude commented
> I am also sure that you don't need my (or anyone else's) help to figure out the reverse problem (given vid and pid, which AVRDUDE serial adapters uniquely specify that combo).

You were absolutely right! I had a look at this challenge with fresh eyes, and I think I managed to implement it in an acceptable way. @mcuee please give this PR all you have 😄 

```
$ ./build_darwin/src/avrdude -cjtag2updi -patmega4809 -P /dev/cu.not_a_port
avrdude OS error: cannot open port /dev/cu.not_a_port: No such file or directory
avrdude error: unable to open programmer jtag2updi on port /dev/cu.not_a_port
Possible candidate serial ports are:
-P /dev/cu.Bluetooth-Incoming-Port
-P /dev/cu.usbserial-A50285BI or -P ft232r:A50285BI
-P /dev/cu.usbmodem14101 or -P usb:2341:0058:426D8DB85151363448202020FF16154A (serial adapter unknown to avrdude.conf)
Note that above ports may not necessarily be connected to a target board or an AVR programmer.
Also note there may be other direct serial ports not listed above.

avrdude done.  Thank you.
```

> trailing serial number but the new serial code matches the start of the serial number. 

I don't think this is necessarily the case. I have two FT232RL chips one has a date code of "1207", while the other one has "2108". The 1207's serial number is A50285BI, while the 2108's is A50285BI. So the second character differs. But I can look into supporting reverse serial numbers with a `...` prefix.

> Speaking of that I would not introduce -P <vid>:<pid>[:<serialnumber>].

No problem! Right now, the `usb:` prefix is optional, but I _can_ make it mandatory if that's important. How about keeping support for both, but promoting `usb:`?

> But yes, this really currently looks like an exciting new super power for AVRDUDE, and thank you for the idea in the first place and for implementing that.

Thanks! And thank you for providing help along the way! I think this will make users that "hand type" Avrdude commands, just like myself, really happy.

What's cool about having libserialport on board is that dealing with "1200 bps touch" (See #1443), like the Arduino Leonardo and Arduino Nano Every require in order to enter "upload mode" would be fairly easy to implement when utilizing libserialport.

* Scan all available serial ports and open the specified serial port at 1200bps to trigger "Upload mode"
* Close the port, and wait a few hundred milliseconds for the device in the other end to re-enumerate
* If a new port (new vid and pid, Arduino Leonardo does this) suddenly appears, try connecting and uploading to this. 
* If no new port appears (Arduino Nano Every act this way), connect to the serial port that has the same VID/PID as the previously used port. The COM port number on Windows may have changed after closing the port the first time, but since we use the VID/PID to determine the path, this doesn't matter!

2023-09-03 20:55 UTC, stefanrueger commented
>  reverse serial numbers 

Or just replace str_starts() with str_ends()? I am neither vested in comparing the start or the end, but I'd like it to be the same as currently in use in some/all of the current  `-P usb:...` code

2023-09-03 20:57 UTC, stefanrueger commented
> "hand type" Avrdude commands

Didn't know there was any other way :wink:

2023-09-03 21:08 UTC, MCUdude commented
> Didn't know there was any other way 😉

I'm thinking about programs like Arduino IDE, which deals with Avrdude "under the hood", and doesn't expose the Avrdude command to the user.

2023-09-04 01:50 UTC, mcuee commented
@MCUdude 

The following seems to be a regression in the latest git.

```
C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1498v2 -C .\avrdude_pr1498v2.conf -c urclock -p m328p -P COM5
avrdude_pr1498v2: AVR device initialized and ready to accept instructions
avrdude_pr1498v2: device signature = 0x1e950f (probably m328p)

avrdude_pr1498v2 done.  Thank you.

C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1498v2 -C .\avrdude_pr1498v2.conf -c urclock -p m328p -P 0x2341:0x0043
avrdude_pr1498v2 error: cannot open port 0x2341:0x0043: The system cannot find the file specified.

avrdude_pr1498v2 error: unable to open programmer urclock on port 0x2341:0x0043
Possible candidate serial ports are:
-P COM3
-P COM5 or -P usb:2341:0043:11352601009369196700 (serial adapter unknown to avrdude.conf)
Note that above ports may not necessarily be connected to a target board or an AVR programmer.
Also note there may be other direct serial ports not listed above.

avrdude_pr1498v2 done.  Thank you.

C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1498v2 -C .\avrdude_pr1498v2.conf -c urclock -p m328p -P 0x2341:0x0043:11352
avrdude_pr1498v2 warning: serial adapter with USB VID 0x0043 and PID 11352 and serial number ï°à└ëå not found
avrdude_pr1498v2 error: cannot open port 0x2341:0x0043:11352: The filename, directory name, or volume label syntax is incorrect.

avrdude_pr1498v2 error: unable to open programmer urclock on port 0x2341:0x0043:11352
Possible candidate serial ports are:
-P COM3
-P COM5 or -P usb:2341:0043:11352601009369196700 (serial adapter unknown to avrdude.conf)
Note that above ports may not necessarily be connected to a target board or an AVR programmer.
Also note there may be other direct serial ports not listed above.

avrdude_pr1498v2 done.  Thank you.

C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1498v2 -C .\avrdude_pr1498v2.conf -c urclock -p m328p -P 0x2341:0x0043:11352601009369196700
avrdude_pr1498v2 warning: serial adapter with USB VID 0x0043 and PID 11352601009369196700 and serial number ï°à└ëå not found
avrdude_pr1498v2 error: cannot open port 0x2341:0x0043:11352601009369196700: The filename, directory name, or volume label syntax is incorrect.

avrdude_pr1498v2 error: unable to open programmer urclock on port 0x2341:0x0043:11352601009369196700
Possible candidate serial ports are:
-P COM3
-P COM5 or -P usb:2341:0043:11352601009369196700 (serial adapter unknown to avrdude.conf)
Note that above ports may not necessarily be connected to a target board or an AVR programmer.
Also note there may be other direct serial ports not listed above.

avrdude_pr1498v2 done.  Thank you.
```

2023-09-04 01:59 UTC, mcuee commented
@MCUdude 

But the following works fine. I think at least serial number should be optional. Partial serial number is not working as of now.

```
C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1498v2 -C .\avrdude_pr1498v2.conf -c urclock -p m328p -P usb:0x2341:0x0043:11352601009369196700
avrdude_pr1498v2: AVR device initialized and ready to accept instructions
avrdude_pr1498v2: device signature = 0x1e950f (probably m328p)

avrdude_pr1498v2 done.  Thank you.

C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1498v2 -C .\avrdude_pr1498v2.conf -c urclock -p m328p -P usb:0x2341:0x0043:113526
avrdude_pr1498v2 warning: serial adapter with USB VID 0x2341 and PID 0x0043 and serial number 113526 not found
avrdude_pr1498v2 error: cannot open port usb:0x2341:0x0043:113526: The filename, directory name, or volume label syntax is incorrect.

avrdude_pr1498v2 error: unable to open programmer urclock on port usb:0x2341:0x0043:113526
Possible candidate serial ports are:
-P COM3
-P COM5 or -P usb:2341:0043:5&E9F3E45&0&5 (serial adapter unknown to avrdude.conf)
Note that above ports may not necessarily be connected to a target board or an AVR programmer.
Also note there may be other direct serial ports not listed above.

avrdude_pr1498v2 done.  Thank you.
```

2023-09-04 02:21 UTC, mcuee commented
@MCUdude 

Hmm, it is strange that port_finder has different output in this laptop (Windows 10) compare to my previous test laptop (Windows 11). This serial number does not seem to be correct.

```
$ ./port_finder.exe uno
Found port:
id:     uno
desc:   Arduino Uno (COM5)
port:   COM5
serno:  5&E9F3E45&0&5

C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1498v2 -C .\avrdude_pr1498v2.conf -c urclock -p m328p -P "usb:0x2341:0x0043:5&E9F3E45&0&5"
avrdude_pr1498v2 warning: serial adapter with USB VID 0x2341 and PID 0x0043 and serial number 5&E9F3E45&0&5 not found
avrdude_pr1498v2 error: cannot open port usb:0x2341:0x0043:5&E9F3E45&0&5: The filename, directory name, or volume label syntax is incorrect.

avrdude_pr1498v2 error: unable to open programmer urclock on port usb:0x2341:0x0043:5&E9F3E45&0&5
Possible candidate serial ports are:
-P COM3
-P COM5 or -P usb:2341:0043:11352601009369196700 (serial adapter unknown to avrdude.conf)
Note that above ports may not necessarily be connected to a target board or an AVR programmer.
Also note there may be other direct serial ports not listed above.

avrdude_pr1498v2 done.  Thank you.

C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1498v2 -C .\avrdude_pr1498v2.conf -c urclock -p m328p -P uno
avrdude_pr1498v2 error: cannot open port uno: The system cannot find the file specified.

avrdude_pr1498v2 error: unable to open programmer urclock on port uno
Possible candidate serial ports are:
-P COM3
-P COM5 or -P usb:2341:0043:11352601009369196700 (serial adapter unknown to avrdude.conf)
Note that above ports may not necessarily be connected to a target board or an AVR programmer.
Also note there may be other direct serial ports not listed above.

avrdude_pr1498v2 done.  Thank you.

C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1498v2 -C .\avrdude_pr1498v2.conf -c urclock -p m328p -P usb:2341:0043:11352601009369196700
avrdude_pr1498v2: AVR device initialized and ready to accept instructions
avrdude_pr1498v2: device signature = 0x1e950f (probably m328p)

avrdude_pr1498v2 done.  Thank you.

C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1498v2 -C .\avrdude_pr1498v2.conf -c urclock -p m328p -P COM5
avrdude_pr1498v2: AVR device initialized and ready to accept instructions
avrdude_pr1498v2: device signature = 0x1e950f (probably m328p)

avrdude_pr1498v2 done.  Thank you.
```

2023-09-04 02:39 UTC, mcuee commented
Still using programmer id is not working for `uno`.

```
C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1498v2 -C .\avrdude_pr1498v2.conf -c urclock -p m328p -P uno
avrdude_pr1498v2 error: cannot open port uno: The system cannot find the file specified.

avrdude_pr1498v2 error: unable to open programmer urclock on port uno
Possible candidate serial ports are:
-P COM3
-P COM5 or -P usb:2341:0043:11352601009369196700 (serial adapter unknown to avrdude.conf)
Note that above ports may not necessarily be connected to a target board or an AVR programmer.
Also note there may be other direct serial ports not listed above.

avrdude_pr1498v2 done.  Thank you.

C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1498v2 -C .\avrdude_pr1498v2.conf -c urclock -p m328p -P uno:11352601009369196700
avrdude_pr1498v2 error: cannot open port uno:11352601009369196700: The system cannot find the file specified.

avrdude_pr1498v2 error: unable to open programmer urclock on port uno:11352601009369196700
Possible candidate serial ports are:
-P COM3
-P COM5 or -P usb:2341:0043:11352601009369196700 (serial adapter unknown to avrdude.conf)
Note that above ports may not necessarily be connected to a target board or an AVR programmer.
Also note there may be other direct serial ports not listed above.

avrdude_pr1498v2 done.  Thank you.
```

2023-09-04 02:58 UTC, mcuee commented
Using Programmer ID seems to work fine for CH340 without serial number.

```
$ ./port_finder.exe ch340
Found port:
id:     ch340
desc:   USB-SERIAL CH340 (COM6)
port:   COM6
serno:

C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1498v2 -C .\avrdude_pr1498v2.conf -c wiring -p m2560 -P ch340
avrdude_pr1498v2: AVR device initialized and ready to accept instructions
avrdude_pr1498v2: device signature = 0x1e9801 (probably m2560)

avrdude_pr1498v2 done.  Thank you.
```

But the following does not work. Again this is the same issue as before, USB Serial Number should be optional.
```
C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1498v2 -C .\avrdude_pr1498v2.conf -c wiring -p m2560 -P usb:0x1a86:0x7523
avrdude_pr1498v2 warning: serial adapter with USB VID 0x1a86 and PID 0x7523 and serial number ï°à└ëå not found
avrdude_pr1498v2 error: cannot open port usb:0x1a86:0x7523: The filename, directory name, or volume label syntax is incorrect.

avrdude_pr1498v2 error: unable to read: The handle is invalid.

avrdude_pr1498v2 error: unable to write: sorry no info avail
avrdude_pr1498v2 error: unable to send command to serial port
avrdude_pr1498v2 error: unable to read: The handle is invalid.

avrdude_pr1498v2 error: timeout
avrdude_pr1498v2 error: unable to write: sorry no info avail
avrdude_pr1498v2 error: unable to send command to serial port
avrdude_pr1498v2 error: unable to read: The handle is invalid.

avrdude_pr1498v2 error: timeout
avrdude_pr1498v2 error: unable to write: sorry no info avail
avrdude_pr1498v2 error: unable to send command to serial port
avrdude_pr1498v2 error: unable to read: The handle is invalid.

avrdude_pr1498v2 error: timeout
avrdude_pr1498v2 error: unable to write: sorry no info avail
avrdude_pr1498v2 error: unable to send command to serial port
avrdude_pr1498v2 error: unable to read: The handle is invalid.

avrdude_pr1498v2 error: timeout
avrdude_pr1498v2 error: unable to write: sorry no info avail
avrdude_pr1498v2 error: unable to send command to serial port
avrdude_pr1498v2 error: unable to read: The handle is invalid.

avrdude_pr1498v2 error: timeout
avrdude_pr1498v2 error: unable to write: sorry no info avail
avrdude_pr1498v2 error: unable to send command to serial port
avrdude_pr1498v2 error: unable to read: The handle is invalid.

avrdude_pr1498v2 error: timeout
avrdude_pr1498v2 error: timeout communicating with programmer
avrdude_pr1498v2 error: unable to open programmer wiring on port usb:0x1a86:0x7523
Possible candidate serial ports are:
-P COM3
-P COM6 or -P ch340
Note that above ports may not necessarily be connected to a target board or an AVR programmer.
Also note there may be other direct serial ports not listed above.

avrdude_pr1498v2 done.  Thank you.
```

2023-09-04 06:27 UTC, MCUdude commented
> The following seems to be a regression in the latest git, compared to earlier version. Looks like the syntax has been changed and the first post needs to be updated.

@mcuee yes, the `usb:` prefix is now mandatory. `-P usb:0x1a86:0x7523`

> Still using programmer id is not working for uno.

`uno` has not been added as a valid serialadapter to avrdude.conf, so you'll have to use the USB VID, PID and the optional serial number for now.

> Using Programmer ID seems to work fine for CH340 without serial number.
... But the following does not work. Again this is the same issue as before, USB Serial Number should be optional.

Great find! This sounds like a regression. I'll look into it.

2023-09-04 06:55 UTC, mcuee commented
FT232R seems to work fine, except that I'd like to have ` -P usb:0403:6001` working as well (serial number is optional).

```
C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1498v2 -C .\avrdude_pr1498v2.conf -c urclock -p m328p -P COM7
avrdude_pr1498v2: AVR device initialized and ready to accept instructions
avrdude_pr1498v2: device signature = 0x1e950f (probably m328p)

avrdude_pr1498v2 done.  Thank you.

C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1498v2 -C .\avrdude_pr1498v2.conf -c urclock -p m328p -P ft232r
avrdude_pr1498v2: AVR device initialized and ready to accept instructions
avrdude_pr1498v2: device signature = 0x1e950f (probably m328p)

avrdude_pr1498v2 done.  Thank you.

C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1498v2 -C .\avrdude_pr1498v2.conf -c urclock -p m328p -P ft232r:A50285BI
avrdude_pr1498v2: AVR device initialized and ready to accept instructions
avrdude_pr1498v2: device signature = 0x1e950f (probably m328p)

avrdude_pr1498v2 done.  Thank you.

C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1498v2 -C .\avrdude_pr1498v2.conf -c urclock -p m328p -P usb:0403:6001
                                                                                                                       
avrdude_pr1498v2 warning: serial adapter with USB VID 0403 and PID 6001 and serial number ï°à└ëå not found
avrdude_pr1498v2 error: cannot open port usb:0403:6001: The filename, directory name, or volume label syntax is incorrect.

avrdude_pr1498v2 error: unable to open programmer urclock on port usb:0403:6001
Possible candidate serial ports are:
-P COM3
-P COM7 or -P ft232r:A50285BI
Note that above ports may not necessarily be connected to a target board or an AVR programmer.
Also note there may be other direct serial ports not listed above.

avrdude_pr1498v2 done.  Thank you.

C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1498v2 -C .\avrdude_pr1498v2.conf -c urclock -p m328p -P usb:0403:6001:A50285BI
avrdude_pr1498v2: AVR device initialized and ready to accept instructions
avrdude_pr1498v2: device signature = 0x1e950f (probably m328p)

avrdude_pr1498v2 done.  Thank you.
```

2023-09-04 07:09 UTC, MCUdude commented
> FT232R seems to work fine, except that I'd like to have  -P usb:0403:6001 working as well (serial number is optional).

Thanks for pointing this out. There was a bug in the [e0abcaf](https://github.com/avrdudes/avrdude/pull/1498/commits/e0abcaf17595e2ad4e92fbace2e6148ff95ef8f2) commit which caused this. Please give it a try with the latest commit!

2023-09-04 08:26 UTC, mcuee commented
> > FT232R seems to work fine, except that I'd like to have  -P usb:0403:6001 working as well (serial number is optional).
> 
> Thanks for pointing this out. There was a bug in the [e0abcaf](https://github.com/avrdudes/avrdude/pull/1498/commits/e0abcaf17595e2ad4e92fbace2e6148ff95ef8f2) commit which caused this. Please give it a try with the latest commit!

Yes it works now.

```
C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1498v3 -C .\avrdude_pr1498v3.conf -c urclock -p m328p -P usb:0403:6001

avrdude_pr1498v3: AVR device initialized and ready to accept instructions
avrdude_pr1498v3: device signature = 0x1e950f (probably m328p)

avrdude_pr1498v3 done.  Thank you.
```

2023-09-04 08:49 UTC, MCUdude commented
Good! The only thing that's missing now is to override the default baud rate if the serial adapter has a predefined baud rate and the user hasn't specified a baud rate using `-b`.

https://github.com/avrdudes/avrdude/blob/431fe61ffabb257df9475d8793fee5fdf93919b0/src/avrdude.conf.in#L2940-L2957

2023-09-04 09:10 UTC, MCUdude commented
@mcuee could you try to dome up with a list of _the most commonly used_ serial adapters (+ USB VID/PID) that I should add?

Here's my suggestions:
* `ch9102`
* `cp210x` (CP2101, CP2102N, CP2104)
* `ft231x`
* `pl2303`
* `uno` , `arduino_uno` or `arduino-uno`
* `mega` , `arduino_mega` or `arduino-mega`

2023-09-04 09:32 UTC, mcuee commented
> @mcuee could you try to dome up with a list of _the most commonly used_ serial adapters (+ USB VID/PID) that I should add?
> 
> Here's my suggestions:
> 
> * `ch340`
> * `ch9102`
> * `cp210x` (CP2101, CP2102N, CP2104)
> * `ft231x`
> * `pl2303`
> * `uno` , `arduino_uno` or `arduino-uno` (CDC-ACM)
> * `mega` , `arduino_mega` or `arduino-mega` (CDC-ACM).

I am okay with the above proposal. 

There are probably others (they could be many based on USB CDC-ACM).
Eg: 
1) `caterina` here, used in Arduino Micro and Leonardo.
https://github.com/arduino/ArduinoCore-avr/tree/master/bootloaders/caterina

2) Microchip's tools also have USB CDC-ACM as part the USB Composite Devices. Not so sure if we want to have `microchip` category.

There is another one mentioned here: HT42B534. I think it is not as popular.
https://github.com/SpenceKonde/AVR-Guidance/blob/master/UPDI/jtag2updi.md

2023-09-04 09:38 UTC, mcuee commented
> EDIT: And perhaps the following if we can get 1200bps touch working (Not the scope of this PR):
> 
> * `leonardo` or `arduino_leonardo`
> * `micro` or `arduino_micro`
> * `nano_every` or `arduino_nano_every`

Yes it will be good to have a separate PR to deal with this 1200bps thingy. libserialport is a good library to deal the issue. So this PR serves as a good foundation for that enhancement as well.

2023-09-04 15:27 UTC, stefanrueger commented
Progress, I now cannot program using the avrdude.conf entry with not-matching serial number. But this PR still displays it as possible candidate:
```
$ avrdude -P mysuperduperboard

avrdude warning: serial adapter mysuperduperboard not found
avrdude OS error: cannot open port mysuperduperboard: No such file or directory
avrdude error: unable to open programmer urclock on port mysuperduperboard
Possible candidate serial ports are:
-P /dev/ttyUSB1 or -P mysuperduperboard
-P /dev/ttyUSB0 or -P ft232r:A600K203
Note that above ports may not necessarily be connected to a target board or an AVR programmer.
Also note there may be other direct serial ports not listed above.

avrdude done.  Thank you.
```

2023-09-04 16:06 UTC, MCUdude commented
> But this PR still displays it as possible candidate:

Correct, I'm working on it.

I should probably also look into how we can prevent printing possible candidates when a previous "not unique" message has already been printed. Right now it is a bit superfluous I think.

```
$ ./build_darwin/src/avrdude -curclock -patmega169 -P ch340
avrdude warning: -P ch340 is not unique; consider one of the below
-P /dev/cu.usbserial-1410 (via ch340 serial adapter)
-P /dev/cu.usbserial-1420 (via ch340 serial adapter)
avrdude warning: serial adapter ch340 not found
avrdude OS error: cannot open port ch340: No such file or directory
avrdude error: unable to open programmer urclock on port ch340
Possible candidate serial ports are:
-P /dev/cu.Bluetooth-Incoming-Port
-P /dev/cu.usbserial-1410 or -P ch340
-P /dev/cu.usbserial-1420 or -P ch340
Note that above ports may not necessarily be connected to a target board or an AVR programmer.
Also note there may be other direct serial ports not listed above.

avrdude done.  Thank you.
```

2023-09-04 20:13 UTC, MCUdude commented
@stefanrueger I've just pushed a commit where only unique USB port details would be suggested.

There are a few workarounds here and there (like adding `sp[i].sernum = cfg_malloc(__func__, 1);` to prevent segfaults).
So if you have suggestions on how the code can be further improved, please let me know!

2023-09-05 01:46 UTC, mcuee commented
@MCUdude 
Now I get segmentation fault.
```
 MINGW64 /c/work/avr/avrdude_test/avrdude_hans/build_mingw64_nt-10.0-19045/src
$ ./avrdude.exe -c urclock -p m328p -P ch340
avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1e950f (probably m328p)

avrdude done.  Thank you.

$ ./avrdude.exe -c urclock -p m328p -P COM4
Segmentation fault

$ ./avrdude.exe -c urclock -p m328p -P usb:0x1a86:0x7523
Segmentation fault
```

2023-09-05 05:24 UTC, MCUdude commented
@mcuee, sorry, I didn't catch that before I went to bed. Hopefully, it should be OK now

2023-09-05 07:31 UTC, mcuee commented
> @mcuee, sorry, I didn't catch that before I went to bed. Hopefully, it should be OK now

Yes the issues have been fixed.
```
C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1498v5 -C .\avrdude_pr1498v5.conf -c urclock -p m328p -P usb:0x1a86:0x7523
avrdude_pr1498v5: AVR device initialized and ready to accept instructions
avrdude_pr1498v5: device signature = 0x1e950f (probably m328p)

avrdude_pr1498v5 done.  Thank you.

C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1498v5 -C .\avrdude_pr1498v5.conf -c urclock -p m328p -P COM4
avrdude_pr1498v5: AVR device initialized and ready to accept instructions
avrdude_pr1498v5: device signature = 0x1e950f (probably m328p)

avrdude_pr1498v5 done.  Thank you.

C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1498v5 -C .\avrdude_pr1498v5.conf -c urclock -p m328p -P ch340
avrdude_pr1498v5: AVR device initialized and ready to accept instructions
avrdude_pr1498v5: device signature = 0x1e950f (probably m328p)

avrdude_pr1498v5 done.  Thank you.
```

2023-09-05 17:29 UTC, stefanrueger commented
@MCUdude Thanks for sterling work.


I noted a *subtle* problem with parsing the `-P string`. The current code parses up to four colon-separated parts, but in case of the `-P serialadapter:serialnumber` notation it should really only be two parts. Otherwise a serial number containing a colon would be cut short at the colon (we don't control serial numbers by manufacturers, and they are free to sprinkle them in).

Another even subtler problem: a new baudrate is taken from a serial adapter *even* when this serial adapter has been rejected by the code. Requires zapping `ser` when not used.

And then there is this:
```
avrdude -P scsi-bus:1a86:7523
avrdude: AVR device initialized and ready to accept instructions
avrdude: device signature = 0x1e950f (probably m328p)

avrdude done.  Thank you.

```

IMO `-P something:<vid>:<pid>[:<sn>]` shouldn't work, only `-P usb:<vid>:<pid>[:<sn>]` should.


As this was easy, I have provided fixes in this [patch 0001-Fix-sublte-parsing-problems.zip](https://github.com/avrdudes/avrdude/files/12526470/0001-Fix-sublte-parsing-problems.zip). Check out to see whether this is OK, and feel free to use.


There are more problems: Somehow, sometimes, there are still wrong boards advertised:

```
$ avrdude -P dunno

avrdude OS error: cannot open port dunno: No such file or directory
avrdude error: unable to open programmer urclock on port dunno
Possible candidate serial ports are:
-P /dev/ttyUSB1 or -P ft232r
-P /dev/ttyUSB0 or -P mysuperduperboard
Note that above ports may not necessarily be connected to a target board or an AVR programmer.
Also note there may be other direct serial ports not listed above.

avrdude done.  Thank you.

$ avrdude -P mysuperduperboard

avrdude warning: serial adapter mysuperduperboard with serial number 777 not found
avrdude OS error: cannot open port mysuperduperboard: No such file or directory
avrdude error: unable to open programmer urclock on port mysuperduperboard
Possible candidate serial ports are:
-P /dev/ttyUSB1 or -P ft232r
-P /dev/ttyUSB0 or -P mysuperduperboard
Note that above ports may not necessarily be connected to a target board or an AVR programmer.
Also note there may be other direct serial ports not listed above.

avrdude done.  Thank you.
```

I have not started reviewing the serialadapter.c code yet; I suspect some problem with the logic there.

Personally, I am a big fan of small functions doing little things well in a re-usable and verifiable way. I have coded a few of them in that [patch 0001-Draft-auxiliary-port-discovery-functions.zip](https://github.com/avrdudes/avrdude/files/12526483/0001-Draft-auxiliary-port-discovery-functions.zip)
 - `static int sa_snmatch(const char *sn, const char *q)` // Is the actual serial number sn matched by the query q?
 - `static int sa_num_matches_by_ids(int vid, int pid, const char *snq, SERPORT *sp, int n);` // Returns how many connected devices are matched by vid, pid and serial number
 - `static int sa_num_matches_by_sea(const SERIALADAPTER *sea, SERPORT *sp, int n);` // Returns how many connected devices are matched by the avrdude.conf serial adapter sea
 - `static int list_matching_serialadapters(SERPORT *target, SERPORT *sp, int n);` // Print " or -P ..." for all avrdude.conf serial adapters uniquely matching the target and return number of matches

I suspect *something like these* might help you getting the logic for the port discovery right. Disclaimer: I have not tested any of them, and you may well want a different granularity of tasks. But I suspect that using functions like these will enable you to write the desired code in a crisper, clearer and easier-to-read way.

Also, I tried to find how the `-P` string is parsed in directly connected USB devices. Seems the serial number is not used! So, we are free to devise our own matching (I must have interpreted @dl8dtl's comment about trailing serial numbers wrongly)! Above matching function for SNs matching makes it a *single* place, so if we like some mechanism better than another during testing we can easily change that.

2023-09-05 18:45 UTC, MCUdude commented
Thanks for the valuable input @stefanrueger! I've applied both patches you provided and will look into how I can improve my code by utilizing the new helper functions.

BTW, what do you think about adding (Arduino) boards as well as serial adapters? Yay or nay?

2023-09-05 19:56 UTC, MCUdude commented
@stefanrueger I think I'm so tied up to how I initially created the logic in `setport_from_serialadapter`and `setport_from_vid_pid` that I'm having a really hard time figuring out how to improve the code using the functions you provided.

For instance, how would you set the `sp[].match flag without the nested loops I'm using?

2023-09-05 22:16 UTC, stefanrueger commented
>  adding (Arduino) boards as well as serial adapters?

I have no real opinion on that. In my view, serial adapters technically translate a mnemonic id to a triplet (vid, pid, sn). As some programmers do the same (amongst other things), programmers could also play this role. And if (Arduino) boards also have a *natural* id to (vid, pid, sn) mapping then, yes, sure.

>  set the `sp[].match` flag

I haven't thought this through, but my thinking was that the *number of matches* functions that I drafted could be used in the following way: if they return 
 - `0` then warn that no such board/serial adapter is plugged in
 - `1` then set the port with the one that matches
 - `> 1` then the result is not unique and list all that match
 
Note I have neither checked nor tested the functions that I drafted. But I imagine they could be enhanced to set the `match` flag en passant, eg, as below
```
typedef struct {
  int vid, pid, match;
  char *sernum, *port;
} SERPORT;

// Set all sp[i].match iff matched by vid, pid and serial number; return number of matches
static int sa_num_matches_by_ids(int vid, int pid, const char *snq, SERPORT *sp, int n) {
  int nm = 0;
  for(int i = 0; i < n; i++)
    nm += sp[i].match = sp[i].vid == vid && sp[i].pid == pid && sa_snmatch(sp[i].sernum, snq);

  return nm;
}
    
// Set all sp[i].match iff matched by the avrdude.conf serial adapter sea; return number of matches
static int sa_num_matches_by_sea(const SERIALADAPTER *sea, SERPORT *sp, int n) {
  int nm;
 
  for(LNODEID pid = lfirst(sea->usbpid); pid; pid = lnext(pid))
    if((nm = sa_num_matches_by_ids(sea->usbvid, *(int *) ldata(pid), sea->usbsn, sp, n)))
      return nm;
   
  return 0;
}
```

These variants would set the `match` component (but it should be an `int` not a `bool`, as the functions add up matches). Note that I use *iff* in the comment to mean *if and only if*. Note also that above functions no longer guard against `sea` or `sp` being NULL, ie, they expect pointers to real things.

2023-09-05 22:30 UTC, stefanrueger commented
Well it's late and the functions above have flaws. The ones below might behave better, but expect the `match` component to be initialised with `0`/false beforehand (as it is when creating the `sp` array).

```
// Set sp[i].match that are matched by vid, pid and serial number; return number of matches
static int sa_num_matches_by_ids(int vid, int pid, const char *snq, SERPORT *sp, int n) {
  int nm = 0;
  for(int i = 0; i < n; i++)
    if(sp[i].vid == vid && sp[i].pid == pid && sa_snmatch(sp[i].sernum, snq)) {
      sp[i].match = 1;
      nm++;
    }
  
  return nm;
}

// Set sp[i].match that are matched by the avrdude.conf serial adapter sea; return number of matches
static int sa_num_matches_by_sea(const SERIALADAPTER *sea, SERPORT *sp, int n) {
  int nm;
  if(sea)
    for(LNODEID pid = lfirst(sea->usbpid); pid; pid = lnext(pid))
      nm += sa_num_matches_by_ids(sea->usbvid, *(int *) ldata(pid), sea->usbsn, sp, n);
  
  return 0;
}
```
Anyway, it's that kind of approach that might decompose the big task into smaller ones.

2023-09-06 07:25 UTC, mcuee commented
No regression as of now.

```
C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1498v6 -C .\avrdude_pr1498v6.conf -c urclock -p m328p -P ch340
avrdude_pr1498v6: AVR device initialized and ready to accept instructions
avrdude_pr1498v6: device signature = 0x1e950f (probably m328p)

avrdude_pr1498v6 done.  Thank you.

C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1498v6 -C .\avrdude_pr1498v6.conf -c urclock -p m328p -P COM4
avrdude_pr1498v6: AVR device initialized and ready to accept instructions
avrdude_pr1498v6: device signature = 0x1e950f (probably m328p)

avrdude_pr1498v6 done.  Thank you.

C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1498v6 -C .\avrdude_pr1498v6.conf -c urclock -p m328p -P usb:0x1a86:0x7523
avrdude_pr1498v6: AVR device initialized and ready to accept instructions
avrdude_pr1498v6: device signature = 0x1e950f (probably m328p)

avrdude_pr1498v6 done.  Thank you.
```

2023-09-06 21:08 UTC, MCUdude commented
I've pushed a few commits where I've hardened the serial number matching logic.

Sorry @stefanrueger but I decided not to spend too much time trying to figure out how to utilize the neat functions you provided. I figured that the bugs in the code pointed out in your earlier post were fairly easy to fix, and I've already spent way too much time trying to rewrite code I find quite easy to read and understand, even though there may be some duplicate code in there.

If you find obvious improvements, feel free to tidy up the code and perhaps break things up into separate functions. But since the code does what it's supposed to, and I find the current "coding style" easier to wrap my head around (probably because I've written it myself), I don't feel like spending much more time on improving code that's good enough for what it's supposed to do.

2023-09-06 23:21 UTC, stefanrueger commented
All good, @MCUdude, anything that floats your boat.

Note, though, the PR still offers `mysuperduperboard` even though it has a serial number that does not match:

```
$ cat ~/.avrduderc

serialadapter parent "ch340"
    id                     = "mysuperduperboard";
    usbsn                  = "777";
;
```
Let's say I plug in two boards, one with a `ch340` and one with a `ft232r`. Then:

```
$ avrdude -P dunno

avrdude OS error: cannot open port dunno: No such file or directory
avrdude error: unable to open programmer urclock on port dunno
Possible candidate serial ports are:
-P /dev/ttyUSB1 or -P ft232r
-P /dev/ttyUSB0 or -P mysuperduperboard
Note that above ports may not necessarily be connected to a target board or an AVR programmer.
Also note there may be other direct serial ports not listed above.

avrdude done.  Thank you.

$ avrdude -P mysuperduperboard

avrdude warning: serial adapter mysuperduperboard with serial number 777 not connected to host
avrdude OS error: cannot open port mysuperduperboard: No such file or directory
avrdude error: unable to open programmer urclock on port mysuperduperboard
Possible candidate serial ports are:
-P /dev/ttyUSB1 or -P ft232r
-P /dev/ttyUSB0 or -P mysuperduperboard
Note that above ports may not necessarily be connected to a target board or an AVR programmer.
Also note there may be other direct serial ports not listed above.

avrdude done.  Thank you.
```

Of the many serial adapters only `-P ch340` from avrdude.conf matches this board uniquely, but the offered `mysuperduperboard` from `.avrduderc` does not.

For my next test I plug in a *second* `ch340` board. Now the output below is almost correct but it should say `via the ch340 serial adapter`, because that's the only serial adapter that in theory could match either board.

```
$ avrdude -P dunno
avrdude OS error: cannot open port dunno: No such file or directory
avrdude error: unable to open programmer urclock on port dunno
Possible candidate serial ports are:
-P /dev/ttyUSB1 or -P ft232r
-P /dev/ttyUSB2 (via mysuperduperboard serial adapter)
-P /dev/ttyUSB0 (via mysuperduperboard serial adapter)
Note that above ports may not necessarily be connected to a target board or an AVR programmer.
Also note there may be other direct serial ports not listed above.

avrdude done.  Thank you.
```

Have you thought about a user who defines several serial adapters of the same type with varying baudrate?

```
$ cat ~/.avrduderc

serialadapter parent "ch340"
    id                     = "ch340-250k";
    baudrate               = 250000;
;

serialadapter parent "ch340"
    id                     = "ch340-115k";
    baudrate               = 115200;
;
```

If I plug in only *one* `ch340` board then there are *three* serial adapters that match: `-P ch340`, `-P ch340-250k` and `-P ch340-115k`. The current PR only prints the *last* one (I think), but that's kinda wrong. Ideally the user is given these three alternatives each of which is able to uniquely address the single board albeit with different baud rate.

2023-09-07 01:51 UTC, mcuee commented
My simple tests are still good with latest git.
```
C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1498v7 -C .\avrdude_pr1498v7.conf -c urclock -p m328p -P ch340
avrdude_pr1498v7: AVR device initialized and ready to accept instructions
avrdude_pr1498v7: device signature = 0x1e950f (probably m328p)

avrdude_pr1498v7 done.  Thank you.

C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1498v7 -C .\avrdude_pr1498v7.conf -c urclock -p m328p -P COM4
avrdude_pr1498v7: AVR device initialized and ready to accept instructions
avrdude_pr1498v7: device signature = 0x1e950f (probably m328p)

avrdude_pr1498v7 done.  Thank you.

C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1498v7 -C .\avrdude_pr1498v7.conf -c urclock -p m328p -P usb:0x7523:0x0264
avrdude_pr1498v7 warning: serial adapter with USB VID 0x7523 and PID 0x0264 not connected
avrdude_pr1498v7 error: cannot open port usb:0x7523:0x0264: The filename, directory name, or volume label syntax is incorrect.

avrdude_pr1498v7 error: unable to open programmer urclock on port usb:0x7523:0x0264
Possible candidate serial ports are:
-P COM3
-P COM4 or -P ch340
Note that above ports may not necessarily be connected to a target board or an AVR programmer.
Also note there may be other direct serial ports not listed above.

avrdude_pr1498v7 done.  Thank you.

C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1498v7 -C .\avrdude_pr1498v7.conf -c urclock -p m328p -P usb:0x1a86:0x7523
avrdude_pr1498v7: AVR device initialized and ready to accept instructions
avrdude_pr1498v7: device signature = 0x1e950f (probably m328p)

avrdude_pr1498v7 done.  Thank you.
```

2023-09-07 17:38 UTC, MCUdude commented
> Of the many serial adapters only -P ch340 from avrdude.conf matches this board uniquely, but the offered mysuperduperboard from .avrduderc does not.

I think I've managed to resolve this in the last commit.

> If I plug in only one ch340 board then there are three serial adapters that match: -P ch340, -P ch340-250k and -P ch340-115k

Good catch! I'll look into this one

2023-09-07 19:35 UTC, MCUdude commented
> If I plug in only one ch340 board then there are three serial adapters that match: -P ch340, -P ch340-250k and -P ch340-115k

`print_available_serialports()` will now print _all_ valid options. I tried _really_ hard to make it separate each option with a comma, but use "or" instead of another comma for the last option. However, I couldn't find a way to make it work for serial adapters that had only two options (/dev path and serial adapter name). @stefanrueger you know it can be done, please let me know!

```
$ ./build_darwin/src/avrdude -curclock -patmega169 -P no_a_port
avrdude OS error: cannot open port no_a_port: No such file or directory
avrdude error: unable to open programmer urclock on port no_a_port
Possible candidate serial ports are:
-P /dev/cu.Bluetooth-Incoming-Port
-P /dev/cu.usbserial-A50285BI, -P ft232r, -P 3D-printer
-P /dev/cu.usbserial-1410, -P ch340, -P ch340-250k, -P ch340-115k
Note that above ports may not necessarily be connected to a target board or an AVR programmer.
Also note there may be other direct serial ports not listed above.

avrdude done.  Thank you.
```

2023-09-07 21:11 UTC, stefanrueger commented
Thank you! Almost there. Still some wrong outputs but we seem to be converging. Plug *one* `ch340` board in and add the following to `~/.avrduderc`.

```
serialadapter parent "ch340"
    id                     = "mysuperduperboard";
    usbsn                  = "777";
;

serialadapter parent "ch340"
    id                     = "myordinaryboard";
    usbsn                  = "888";
;

serialadapter parent "ch340"
    id                     = "ch340-115k";
    baudrate               = 115200;
;
```

Then test
```
$ avdude -P dunno

avrdude OS error: cannot open port dunno: No such file or directory
avrdude error: unable to open programmer urclock on port dunno
Possible candidate serial ports are:
-P /dev/ttyUSB0, -P ch340, -P mysuperduperboard, -P myordinaryboard, -P ch340-115k
Note that above ports may not necessarily be connected to a target board or an AVR programmer.
Also note there may be other direct serial ports not listed above.

avrdude done.  Thank you.
```

`myordinaryboard` and `mysuperdperboard` should not appear in the list as they don't match.

> separate each option with a comma, but use "or" instead of another comma for the last option

Not to worry a list is fine; if you want to use an or instead of a comma, you'd have to have a sense of a list length or have a list available that you can look ahead by an element to figure out whether you are at the penultimate element; I agree that is *really* hard if you don't want to split things into small functions.

2023-09-08 13:20 UTC, MCUdude commented
> Thank you! Almost there. Still some wrong outputs but we seem to be converging. Plug one ch340 board in and add the following to ~/.avrduderc.

Thanks for pointing this out. I was sure this issue was fixed, but I'll look at it again. The other bug that _has_ to be fixed before this PR can be considered merged is to get make/autoconf working. @dl8dtl do you think you than have a look at this; I have absolutely no clue how to fix it...

<details>
<summary>make error</summary>

```
make
/Library/Developer/CommandLineTools/usr/bin/make  all-recursive
Making all in .
  CC       avrdude-main.o
  CC       libavrdude_a-serialadapter.o
  AR       libavrdude.a
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libavrdude.a(libavrdude_a-confwin.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libavrdude.a(libavrdude_a-ppi.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libavrdude.a(libavrdude_a-ppiwin.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libavrdude.a(libavrdude_a-serbb_win32.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libavrdude.a(libavrdude_a-ser_win32.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libavrdude.a(libavrdude_a-confwin.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libavrdude.a(libavrdude_a-ppi.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libavrdude.a(libavrdude_a-ppiwin.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libavrdude.a(libavrdude_a-serbb_win32.o) has no symbols
/Library/Developer/CommandLineTools/usr/bin/ranlib: file: libavrdude.a(libavrdude_a-ser_win32.o) has no symbols
  CCLD     avrdude
ld: warning: directory not found for option '-FCoreFoundation'
Undefined symbols for architecture x86_64:
  "_sp_free_port_list", referenced from:
      _find_serialport_adapter in libavrdude.a(libavrdude_a-serialadapter.o)
      _find_serialport_vid_pid in libavrdude.a(libavrdude_a-serialadapter.o)
  "_sp_get_port_name", referenced from:
      _find_serialport_adapter in libavrdude.a(libavrdude_a-serialadapter.o)
      _find_serialport_vid_pid in libavrdude.a(libavrdude_a-serialadapter.o)
  "_sp_get_port_usb_serial", referenced from:
      _find_serialport_adapter in libavrdude.a(libavrdude_a-serialadapter.o)
      _find_serialport_vid_pid in libavrdude.a(libavrdude_a-serialadapter.o)
  "_sp_get_port_usb_vid_pid", referenced from:
      _find_serialport_adapter in libavrdude.a(libavrdude_a-serialadapter.o)
      _find_serialport_vid_pid in libavrdude.a(libavrdude_a-serialadapter.o)
  "_sp_list_ports", referenced from:
      _find_serialport_adapter in libavrdude.a(libavrdude_a-serialadapter.o)
      _find_serialport_vid_pid in libavrdude.a(libavrdude_a-serialadapter.o)
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [avrdude] Error 1
make[1]: *** [all-recursive] Error 1
make: *** [all] Error 2
```

</details>

> If you want to use an or instead of a comma, you'd have to have a sense of a list length or have a list available that you can look ahead by an element to figure out whether you are at the penultimate element; I agree that is really hard if you don't want to split code into small functions.

It's not that I don't _want_ to split things into functions, it's just that I find it increasingly difficult to follow the program flow and figure out what's going on. I still consider myself a rookie C programmer, and this is the kind of thing I'd like to become better at. I've seen the magical things you're able to accomplish using this technique (-t/-T implementation and urclock, for instance).

Again, once I'm finished fixing the last(?) bug, it would be really great if you would like to do some finishing touches so I can see how something _I_ wrote and understand can be transformed into smaller functions that are highly reusable.

Bottomline:
Projects like these are the most fun. The end goal is very clear, and _will_ make the "Avrdude experience" better for those who are using USB to serial-based programmers. Having someone who is way more experienced than I am and who can come up with useful ideas and improvements, but can also provide some guidance if I get stuck, is something I find very valuable.

So thank you for your patience and your knowledge @stefanrueger! And a big thanks to @mcuee who's always there when testing is needed.

2023-09-10 20:21 UTC, MCUdude commented
I managed to fix the build issues with autoconf/make and added some information regarding serial port discovery to the docs. I think this PR is ready for review!

2023-09-11 04:15 UTC, mcuee commented
Nice, I can build avrdude using the auto-tools as well, there is only one warning about dynamic library.
```
libtool: warning: undefined symbols not allowed in x86_64-w64-mingw32 shared libraries; building static only
```

<details>
<summary> build log under MSYS2 mingw64</summary>

```
 MINGW64 /c/work/avr/avrdude_test/avrdude_hans/src
$ ./bootstrap
+ rm -rf autom4te.cache
+ LIBTOOLIZE=libtoolize
+ glibtoolize --version
+ libtoolize
libtoolize: putting auxiliary files in '.'.
libtoolize: linking file './ltmain.sh'
libtoolize: putting macros in AC_CONFIG_MACRO_DIRS, 'm4'.
libtoolize: linking file 'm4/libtool.m4'
libtoolize: linking file 'm4/ltoptions.m4'
libtoolize: linking file 'm4/ltsugar.m4'
libtoolize: linking file 'm4/ltversion.m4'
libtoolize: linking file 'm4/lt~obsolete.m4'
+ aclocal
+ autoheader
+ autoconf
configure.ac:46: warning: AC_PROG_LEX without either yywrap or noyywrap is obsolete
../autoconf-2.71/lib/autoconf/programs.m4:716: _AC_PROG_LEX is expanded from...
../autoconf-2.71/lib/autoconf/programs.m4:709: AC_PROG_LEX is expanded from...
configure.ac:46: the top level
configure.ac:123: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:123: You should run autoupdate.
../autoconf-2.71/lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
configure.ac:123: the top level
configure.ac:243: warning: The macro `AC_HEADER_TIME' is obsolete.
configure.ac:243: You should run autoupdate.
../autoconf-2.71/lib/autoconf/headers.m4:743: AC_HEADER_TIME is expanded from...
configure.ac:243: the top level
configure.ac:265: warning: The macro `AC_TRY_LINK' is obsolete.
configure.ac:265: You should run autoupdate.
../autoconf-2.71/lib/autoconf/general.m4:2920: AC_TRY_LINK is expanded from...
configure.ac:265: the top level
configure.ac:297: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:297: You should run autoupdate.
../autoconf-2.71/lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
configure.ac:297: the top level
configure.ac:315: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:315: You should run autoupdate.
../autoconf-2.71/lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
configure.ac:315: the top level
configure.ac:327: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:327: You should run autoupdate.
../autoconf-2.71/lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
configure.ac:327: the top level
configure.ac:339: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:339: You should run autoupdate.
../autoconf-2.71/lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
configure.ac:339: the top level
configure.ac:351: warning: The macro `AC_HELP_STRING' is obsolete.
configure.ac:351: You should run autoupdate.
../autoconf-2.71/lib/autoconf/general.m4:204: AC_HELP_STRING is expanded from...
configure.ac:351: the top level
configure.ac:474: warning: The macro `AC_TRY_COMPILE' is obsolete.
configure.ac:474: You should run autoupdate.
../autoconf-2.71/lib/autoconf/general.m4:2847: AC_TRY_COMPILE is expanded from...
configure.ac:474: the top level
configure.ac:499: warning: The macro `AC_TRY_COMPILE' is obsolete.
configure.ac:499: You should run autoupdate.
../autoconf-2.71/lib/autoconf/general.m4:2847: AC_TRY_COMPILE is expanded from...
configure.ac:499: the top level
configure.ac:523: warning: The macro `AC_TRY_LINK' is obsolete.
configure.ac:523: You should run autoupdate.
../autoconf-2.71/lib/autoconf/general.m4:2920: AC_TRY_LINK is expanded from...
configure.ac:523: the top level
+ automake -a -c
configure.ac:37: installing './compile'
configure.ac:28: installing './config.guess'
configure.ac:28: installing './config.sub'
configure.ac:33: installing './install-sh'
configure.ac:33: installing './missing'
Makefile.am: installing './depcomp'
configure.ac: installing './ylwrap'
doc/Makefile.am:33: installing 'doc/mdate-sh'
doc/Makefile.am:33: installing 'doc/texinfo.tex'

$ ./configure --prefix=/mingw64
configure: loading site script /etc/config.site
checking build system type... x86_64-w64-mingw32
checking host system type... x86_64-w64-mingw32
checking target system type... x86_64-w64-mingw32
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a race-free mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking how to print strings... printf
checking whether make supports the include directive... yes (GNU style)
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether the compiler supports GNU C... yes
checking whether gcc accepts -g... yes
checking for gcc option to enable C11 features... none needed
checking whether gcc understands -c and -o together... yes
checking dependency style of gcc... gcc3
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... C:/msys64/mingw64/x86_64-w64-mingw32/bin/ld.exe
checking if the linker (C:/msys64/mingw64/x86_64-w64-mingw32/bin/ld.exe) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /mingw64/bin/nm -B
checking the name lister (/mingw64/bin/nm -B) interface... BSD nm
checking whether ln -s works... no, using cp -pR
checking the maximum length of command line arguments... 8192
checking how to convert x86_64-w64-mingw32 file names to x86_64-w64-mingw32 format... func_convert_file_msys_to_w32
checking how to convert x86_64-w64-mingw32 file names to toolchain format... func_convert_file_msys_to_w32
checking for C:/msys64/mingw64/x86_64-w64-mingw32/bin/ld.exe option to reload object files... -r
checking for file... file
checking for objdump... objdump
checking how to recognize dependent libraries... file_magic ^x86 archive import|^x86 DLL
checking for dlltool... dlltool
checking how to associate runtime and link libraries... func_cygming_dll_for_implib
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /mingw64/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking for stdio.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for strings.h... yes
checking for sys/stat.h... yes
checking for sys/types.h... yes
checking for unistd.h... yes
checking for sys/time.h... yes
checking for dlfcn.h... no
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -DDLL_EXPORT -DPIC
checking if gcc PIC flag -DDLL_EXPORT -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (C:/msys64/mingw64/x86_64-w64-mingw32/bin/ld.exe) supports shared libraries... yes
checking whether -lc should be explicitly linked in... yes
checking dynamic linker characteristics... Win32 ld.exe
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking whether make supports nested variables... (cached) yes
checking for gcc... (cached) gcc
checking wheth [...]

2023-09-11 04:16 UTC, mcuee commented
Missing features -- MSVC CMake build with libserialport. But that can be delayed and outside of this PR.

Hopefully @mariusgreuel can come back sometime to give the advice on MSVC build.

2023-09-12 01:38 UTC, mcuee commented
No regressions found so far, for the latest version.

```
C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1498v8 -C .\avrdude_pr1498v8.conf -c urclock -p m328p -P ch340
avrdude_pr1498v8: AVR device initialized and ready to accept instructions
avrdude_pr1498v8: device signature = 0x1e950f (probably m328p)

avrdude_pr1498v8 done.  Thank you.

C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1498v8 -C .\avrdude_pr1498v8.conf -c urclock -p m328p -P COM4
avrdude_pr1498v8: AVR device initialized and ready to accept instructions
avrdude_pr1498v8: device signature = 0x1e950f (probably m328p)

avrdude_pr1498v8 done.  Thank you.

C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1498v8 -C .\avrdude_pr1498v8.conf -c urclock -p m328p -P usb:1a86:7523

avrdude_pr1498v8: AVR device initialized and ready to accept instructions
avrdude_pr1498v8: device signature = 0x1e950f (probably m328p)

avrdude_pr1498v8 done.  Thank you.
```

2023-09-12 16:38 UTC, stefanrueger commented
> requested a review

I have reviewed main.c and suggest the following [-P parsing improvement patch](https://github.com/avrdudes/avrdude/files/12588709/0001-Improve-P-serial-adapter-string-parsing.zip); this improves on my previous code in that it truly leaves the optional serial number intact no matter how many colons it contains. I currently don't have a lot of time to go through the relatively complex serialadapter.c code; maye @MCUdude  finds a way of simplifying/refactoring the code in the meantime? The earliest I can look at the code in earnest would be after the w/end.

2023-09-13 05:32 UTC, mcuee commented
I will see if I can carry out some sanity check on FreeBSD, NetBSD and OpenBSD as well, probably over the weekend.

2023-09-13 22:26 UTC, MCUdude commented
I'm slowly going though the existing code and trying to rewrite some of it to make it appear less complex and thus makes it easier to maintain.

@stefanrueger I _think_ `setport_from_serialadapter()`and `setport_from_vid_pid()` are good to go. @mcuee may confirm this. I'll have to wait with `print_available_serialports()` for another day.

2023-09-14 02:37 UTC, mcuee commented
No regression under Windows so I guess the latest change is okay.
```
C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1498v9 -C .\avrdude_pr1498v9.conf -c urclock -p m328p -P usb:1a86:7523

avrdude_pr1498v9: AVR device initialized and ready to accept instructions
avrdude_pr1498v9: device signature = 0x1e950f (probably m328p)

avrdude_pr1498v9 done.  Thank you.

C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1498v9 -C .\avrdude_pr1498v9.conf -c urclock -p m328p -P COM4
avrdude_pr1498v9: AVR device initialized and ready to accept instructions
avrdude_pr1498v9: device signature = 0x1e950f (probably m328p)

avrdude_pr1498v9 done.  Thank you.

C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1498v9 -C .\avrdude_pr1498v9.conf -c urclock -p m328p -P ch340
avrdude_pr1498v9: AVR device initialized and ready to accept instructions
avrdude_pr1498v9: device signature = 0x1e950f (probably m328p)

avrdude_pr1498v9 done.  Thank you.
```

2023-09-14 07:32 UTC, MCUdude commented
Thanks for testing @mcuee!
It looks like I can further simply `setport_from_serialadapter() `and `setport_from_vid_pid()` (completely remove the need for a `matches` flag).

I should probably also provide some instructions and some test commands to properly "stress-test" the code. I'll see what I can do this evening.

2023-09-17 01:39 UTC, mcuee commented
No regression under Windows.
```
PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1498v10 -C .\avrdude_pr1498v10.conf -c urclock -p m328p -P COM42
avrdude_pr1498v10: AVR device initialized and ready to accept instructions
avrdude_pr1498v10: device signature = 0x1e950f (probably m328p)

avrdude_pr1498v10 done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1498v10 -C .\avrdude_pr1498v10.conf -c urclock -p m328p -P ft232r
avrdude_pr1498v10: AVR device initialized and ready to accept instructions
avrdude_pr1498v10: device signature = 0x1e950f (probably m328p)

avrdude_pr1498v10 done.  Thank you.

PS C:\work\avr\avrdude_test\avrdude_bin> .\avrdude_pr1498v10 -C .\avrdude_pr1498v10.conf -c urclock -p m328p -P usb:0x0403:0x6001
avrdude_pr1498v10: AVR device initialized and ready to accept instructions
avrdude_pr1498v10: device signature = 0x1e950f (probably m328p)

avrdude_pr1498v10 done.  Thank you.
```

2023-09-17 02:15 UTC, mcuee commented
No issues under Linux as well (Ubuntu 20.04).

```
mcuee@UbuntuSwift3 ~/build/avr/avrdude_bin $ ./avrdude_pr1498v10 -C ./avrdude_pr1498v10.conf -c urclock -p m328p -P ft232r
avrdude_pr1498v10: AVR device initialized and ready to accept instructions
avrdude_pr1498v10: device signature = 0x1e950f (probably m328p)

avrdude_pr1498v10 done.  Thank you.

mcuee@UbuntuSwift3 ~/build/avr/avrdude_bin $ ./avrdude_pr1498v10 -C ./avrdude_pr1498v10.conf -c urclock -p m328p -P /dev/ttyUSB0 
avrdude_pr1498v10: AVR device initialized and ready to accept instructions
avrdude_pr1498v10: device signature = 0x1e950f (probably m328p)

avrdude_pr1498v10 done.  Thank you.

mcuee@UbuntuSwift3 ~/build/avr/avrdude_bin $ ./avrdude_pr1498v10 -C ./avrdude_pr1498v10.conf -c urclock -p m328p -P usb:0x0403:0x6001
avrdude_pr1498v10: AVR device initialized and ready to accept instructions
avrdude_pr1498v10: device signature = 0x1e950f (probably m328p)

avrdude_pr1498v10 done.  Thank you.
```

2023-09-17 17:50 UTC, stefanrueger commented
@MCUdude I've reviewed the serialadapter.c code. There are still edge cases: plugged in one ft232r and two ch340. `avrdude -P dunno` correctly tells me:
```
avrdude OS error: cannot open port dunno: No such file or directory
avrdude error: unable to open programmer urclock on port dunno
Possible candidate serial ports are:
-P /dev/ttyUSB1 (via ch340 serial adapter)
-P /dev/ttyUSB2, -P ft232r
-P /dev/ttyUSB0 (via ch340 serial adapter)
Note that above ports may not necessarily be connected to a target board or an AVR programmer.
Also note there may be other direct serial ports not listed above.
```

However, when I specify the ambiguous `-P ch340` I would expect only the two ch340 ports to be listed, but three are listed, one of which superfluous (and wrong):
```
$ avrdude -P ch340
avrdude warning: -P ch340 is not unique; consider one of the below
-P /dev/ttyUSB1 (via ch340 serial adapter)
-P /dev/ttyUSB2 or -P ch340:A600K203
-P /dev/ttyUSB0 (via ch340 serial adapter)
avrdude OS error: cannot open port ch340: No such file or directory
avrdude error: unable to open programmer urclock on port ch340
```

I thought it might be best to decompose the code into a structure that is closer to the problem at hand. Here a 
[patch 0001-Refactor-serialadapter.c.zip](https://github.com/avrdudes/avrdude/files/12643371/0001-Refactor-serialadapter.c.zip). No guarantees; this needs thoroughly reviewing and thoroughly testing!

2023-09-17 19:30 UTC, MCUdude commented
> However, when I specify the ambiguous -P ch340 I would expect only the two ch340 ports to be listed, but three are listed, one of which superfluous (and wrong):

Fixed.

> However, when I specify the ambiguous -P ch340 I would expect only the two ch340 ports to be listed, but three are listed, one of which superfluous (and wrong):

I need to borrow a big USB hub from work to iron this out. I'm sure it can be done. Thanks for pointing this out.

> I thought it might be best to decompose the code into a structure that is closer to the problem at hand. Here a
[patch 0001-Refactor-serialadapter.c.zip](https://github.com/avrdudes/avrdude/files/12643371/0001-Refactor-serialadapter.c.zip). No guarantees; this needs thoroughly reviewing and thoroughly testing!

I had a look at the patch, and I have to admit I have mixed feelings. On one side, I'm sure the remaining issues from my core are gone, but on the other side, I don't think there are that many issues left in the first place. On the other side, the code is very different from my approach, and even though it sure is more clever, I find it more complicated and unfamiliar at first glance (I'm sure this the latter will change).

Don't get me wrong, I'm very happy about all the feedback I've gotten while working on the for the last two or three weeks, but it feels a little wistful to merge a patch at the very end that replaces most of the underlying functionality I've spent all this time figuring out myself.

I'll spend some time reading through the patch to figure out exactly what's going on, while still having #1500 in the back of my head.

2023-09-17 21:19 UTC, stefanrueger requested changes

2023-09-17 21:19 UTC, stefanrueger commented on src/serialadapter.c
> +        if (sp[i].unique && sp[i].sernum[0])
How can `sp[i].match` and `sp[i].unique` determine whether `ser` is ambiguous wrt to the plugged-in devices? 

These flags *cannot possibly know this* as they have *never* seen `ser` at all; when they were computed in `get_libserialport_data()` that function *only* had the plugged-in devices to look at. `match` and `unique` are *not* useful for the problem of matching a *user-specified* adapter. This code cannot possibly work. It's the wrong structure.

And it does not work: I have just plugged in four devices, two ft232r with different serial number and two ch340 without serial numbers. Here the classic test `avrdude -P dunno` output, which is correct on this occasion:
```
avrdude OS error: cannot open port dunno: No such file or directory
avrdude error: unable to open programmer urclock on port dunno
Possible candidate serial ports are:
-P /dev/ttyUSB3, -P ft232r:MCU8
-P /dev/ttyUSB1 (via ch340 serial adapter)
-P /dev/ttyUSB2, -P ft232r:A600K203
-P /dev/ttyUSB0 (via ch340 serial adapter)
Note that above ports may not necessarily be connected to a target board or an AVR programmer.
Also note there may be other direct serial ports not listed above.
```

Now I test
```
$ avrdude -P ch340
avrdude warning: -P ch340 is not unique; consider one of the below
-P /dev/ttyUSB3 or -P ch340:MCU8
-P /dev/ttyUSB1 (via ch340 serial adapter)
-P /dev/ttyUSB2 or -P ch340:A600K203
-P /dev/ttyUSB0 (via ch340 serial adapter)
avrdude OS error: cannot open port ch340: No such file or directory
avrdude error: unable to open programmer urclock on port ch340
```
Half of the output is wrong on more than one level. And the same happens with
```
$ avrdude -P ft232r
avrdude warning: -P ft232r is not unique; consider one of the below
-P /dev/ttyUSB3 or -P ft232r:MCU8
-P /dev/ttyUSB1 (via ft232r serial adapter)
-P /dev/ttyUSB2 or -P ft232r:A600K203
-P /dev/ttyUSB0 (via ft232r serial adapter)
avrdude OS error: cannot open port ft232r: No such file or directory
avrdude error: unable to open programmer urclock on port ft232r
```

The reason for this is that the `match`, `unique` and `known` flags are not needed and their use yields the wrong outputs.  The current code needs some fundamental change.

2023-09-18 19:15 UTC, MCUdude commented
I've connected 12 USB to serial devices to test your patch @stefanrueger. The first issue I've encountered is that it seems like it doesn't print "native" ports; ports that are built-in and don't have a VID/PID. I think these should be printed if the user has specified an unknown port.

Apart from this, I've not encountered any issues.

Initially, there should have been a lot more "duplicate" Arduino boards, but I was so dumb and connected a 12V port to the USB hub, which ended up frying four boards. So I've ordered 3x ATmega16U2 chips and an ATmega32U4 to fix the broken boards. Luckily, I only fried one target microcontroller, and this was only an ATmega328P in a socket, so that's not a big loss.

I've connected the following devices:
* 3x CH340 boards without serial numbers
* 3x FT232R boards with unique serial numbers
* 1x Arduino UNO Wifi rev2 (usb:03eb:2145:11B050488B1C13A05D65)
* 1x Arduino Nano Every
* 1x Arduino UNO (usb:2341:0043)
* 1x Curiosity Nano ATmega4809 (usb:03eb:2175)
* 1x MicroUPDI programmer (mEDBG/UNO Wifi Rev2 with custom SN)
* ATEN UC232A RS232 adapter (usb:0557:2008)

<details>
<summary>Output with all adapters connected</summary>

```
$ cat ~/.avrduderc 
default_programmer = "usbasp";
default_serial     = "/dev/cu.usbserial-1410";
#allow_subshells    = yes;

serialadapter parent "ch340"
    id                     = "ch340-250k";
    baudrate               = 250000;
;

serialadapter parent "ch340"
    id                     = "ch340-500k";
    baudrate               = 500000;
;

serialadapter parent "ft232r"
    id                     = "3d-printer";
    usbsn                  = "A60408VE";
    baudrate               = 230400;
;

serialadapter parent "ft232r"
    id                     = "xmega-dev-board";
    baudrate               = 57600;
;

serialadapter
    id                     = "nano-every";
    desc                   = "Arduino Nano Every";
    usbvid                 = 0x2341;
    usbpid                 = 0x0058;
;

$ ./avrdude -curclock -patmega328p -P dunno
avrdude OS error: cannot open port dunno: No such file or directory
avrdude error: unable to open programmer urclock on port dunno
Possible candidate serial ports are:
  -P /dev/cu.usbmodem1424302 or -P usb:03eb:2145:MICROUPDIPROGRAMMERX
  -P /dev/cu.usbmodem142301 or -P nano-every
  -P /dev/cu.usbmodem1421401 or -P usb:2341:0043
  -P /dev/cu.usbserial-142420 (via ch340 serial adapter)
  -P /dev/cu.usbserial-142410 (via ch340 serial adapter)
  -P /dev/cu.usbserial-142440 (via ch340 serial adapter)
  -P /dev/cu.usbserial-A60408VE, -P ft232r:A60408VE, -P 3d-printer or -P xmega-dev-board:A60408VE
  -P /dev/cu.usbserial-AH00M3HQ, -P ft232r:AH00M3HQ, -P 3d-printer:AH00M3HQ or -P xmega-dev-board:AH00M3HQ
  -P /dev/cu.usbmodem142202 or -P usb:03eb:2145:11B050488B1C13A05D65
  -P /dev/cu.usbserial-A50285BI, -P ft232r:A50285BI, -P 3d-printer:A50285BI or -P xmega-dev-board:A50285BI
  -P /dev/cu.usbmodem141202 or -P usb:03eb:2175
  -P /dev/cu.UC-232AC or -P usb:0557:2008
Note that above ports might not be connected to a target board or an AVR programmer.
Also note there may be other direct serial ports not listed above.

avrdude done.  Thank you.

$ ./avrdude -curclock -patmega328p -P ch340
avrdude warning: -P ch340 is ambiguous; consider
  -P /dev/cu.usbserial-142420 (via ch340 serial adapter)
  -P /dev/cu.usbserial-142410 (via ch340 serial adapter)
  -P /dev/cu.usbserial-142440 (via ch340 serial adapter)
avrdude OS error: cannot open port ch340: No such file or directory
avrdude error: unable to open programmer urclock on port ch340

avrdude done.  Thank you.

$ ./avrdude -curclock -patmega328p -P ft232r
avrdude warning: -P ft232r is ambiguous; consider
  -P /dev/cu.usbserial-A60408VE, -P ft232r:A60408VE, -P 3d-printer or -P xmega-dev-board:A60408VE
  -P /dev/cu.usbserial-AH00M3HQ, -P ft232r:AH00M3HQ, -P 3d-printer:AH00M3HQ or -P xmega-dev-board:AH00M3HQ
  -P /dev/cu.usbserial-A50285BI, -P ft232r:A50285BI, -P 3d-printer:A50285BI or -P xmega-dev-board:A50285BI
avrdude OS error: cannot open port ft232r: No such file or directory
avrdude error: unable to open programmer urclock on port ft232r

avrdude done.  Thank you.

$ ./avrdude -curclock -patmega328p -P nano-every
avrdude warning: attempt 1 of 10: not in sync
avrdude warning: attempt 2 of 10: not in sync
avrdude warning: attempt 3 of 10: not in sync
^C

$ ./avrdude -curclock -patmega328p -P ft232r:AH00M3HQ
avrdude warning: attempt 1 of 10: not in sync
avrdude warning: attempt 2 of 10: not in sync
avrdude warning: attempt 3 of 10: not in sync
avrdude warning: attempt 4 of 10: not in sync
^C

$ ./avrdude -curclock -patmega328p -P xmega-dev-board:A60408VE
avrdude warning: attempt 1 of 10: not in sync
avrdude warning: attempt 2 of 10: not in sync
avrdude warning: attempt 3 of 10: not in sync
^C
```

</details>


<details>

<summary>In the next step I disconnected all adapters except for the FT232R ones:</summary>

```
$ ./avrdude -curclock -patmega328p -P dunno
avrdude OS error: cannot open port dunno: No such file or directory
avrdude error: unable to open programmer urclock on port dunno
Possible candidate serial ports are:
  -P /dev/cu.usbserial-A60408VE, -P ft232r:A60408VE, -P 3d-printer or -P xmega-dev-board:A60408VE
  -P /dev/cu.usbserial-AH00M3HQ, -P ft232r:AH00M3HQ, -P 3d-printer:AH00M3HQ or -P xmega-dev-board:AH00M3HQ
  -P /dev/cu.usbserial-A50285BI, -P ft232r:A50285BI, -P 3d-printer:A50285BI or -P xmega-dev-board:A50285BI
Note that above ports might not be connected to a target board or an AVR programmer.
Also note there may be other direct serial ports not listed above.

avrdude done.  Thank you.

$ ./avrdude -curclock -patmega328p -P ft232r
avrdude warning: -P ft232r is ambiguous; consider
  -P /dev/cu.usbserial-A60408VE, -P ft232r:A60408VE, -P 3d-printer or -P xmega-dev-board:A60408VE
  -P /dev/cu.usbserial-AH00M3HQ, -P ft232r:AH00M3HQ, -P 3d-printer:AH00M3HQ or -P xmega-dev-board:AH00M3HQ
  -P /dev/cu.usbserial-A50285BI, -P ft232r:A50285BI, -P 3d-printer:A50285BI or -P xmega-dev-board:A50285BI
avrdude OS error: cannot open port ft232r: No such file or directory
avrdude error: unable to open programmer urclock on port ft232r

avrdude done.  Thank you.

$ ./avrdude -curclock -patmega328p -P ft232r:A
avrdude warning: -P ft232r:A is ambiguous; consider
  -P /dev/cu.usbserial-A60408VE, -P ft232r:A60408VE, -P 3d-printer or -P xmega-dev-board:A60408VE
  -P /dev/cu.usbserial-AH00M3HQ, -P ft232r:AH00M3HQ, -P 3d-printer:AH00M3HQ or -P xmega-dev-board:AH00M3HQ
  -P /dev/cu.usbserial-A50285BI, -P ft232r:A50285BI, -P 3d-printer:A50285BI or -P xmega-dev-board:A50285BI
avrdude OS error: cannot open port ft232r:A: No such file or directory
avrdude error: unable to open programmer urclock on port ft232r:A

avrdude done.  Thank you.

$ ./avrdude -curclock -patmega328p -P ft232r:A6
avrdude warning: attempt 1 of 10: not in sync
avrdude warning: attempt 2 of 10: not in sync
avrdude warning: attempt 3 of 10: not in sync
^C

$ ./avrdude -curclock -patmega328p -P ft232r:...I
avrdude warning: attempt 1 of 10: not in sync
avrdude warning: attempt 2 of 10: not in sync
^C

$ ./avrdude -curclock -patmega328p -P ft232r:...q
avrdude warning: -P ft232r:...q is not connected; consider
  -P /dev/cu.usbserial-A60408VE, -P ft232r:A60408VE, -P 3d-printer or -P xmega-dev-board:A60408VE
  -P /dev/cu.usbserial-AH00M3HQ, -P ft232r:AH00M3HQ, -P 3d-printer:AH00M3HQ or -P xmega-dev-board:AH00M3HQ
  -P /dev/cu.usbserial-A50285BI, -P ft232r:A50285BI, -P 3d-printer:A50285BI or -P xmega-dev-board:A50285BI
avrdude OS error: cannot open port ft232r:...q: No such file or directory
avrdude error: unable to open programmer urclock on port ft232r:...q

avrdude done.  Thank you.

$ ./avrdude -curclock -patmega328p -P 3d-printer
avrdude warning: attempt 1 of 10: not in sync
avrdude warning: attempt 2 of 10: not in sync
avrdude warning: attempt 3 of 10: not in sync
^C

$ ./avrdude -curclock -patmega328p -P 3d-printer:A5
avrdude warning: attempt 1 of 10: not in sync [...]

2023-09-18 20:42 UTC, stefanrueger commented
@MCUdude Brilliant stress tests! ... and commiseration re the fry-up :-(

The tests have uncovered another problem: the order of the ports look somewhat unknown/unsystematic/weird. How about sorting according to the port string in a way that `/dev/ttyUSB7` comes before `/dev/ttyUSB10` (ie, separate initial string from trailing number, then sort by initial string first and then numerically by trailing number)? 

I have rustled up a patch to sort the list: [0001-Sort-list-of-plugged-in-SERPORTs-according-to-port.zip](https://github.com/avrdudes/avrdude/files/12653336/0001-Sort-list-of-plugged-in-SERPORTs-according-to-port.zip)

With #1500 in mind, where you need a list of SERPORTS in the new list that were not in the old list, I have added in above patch a function `SERPORT **sa_spa_not_spb()` that does exactly that.

> doesn't print "native" ports; ports that are built-in and don't have a VID/PID

Yes, I wondered about this, too. I have started to check the libserialport library to see how one could get these but have not made progress. This is why the current version prints Also note there may be other direct serial ports not listed above.

2023-09-18 20:46 UTC, stefanrueger approved these changes

2023-09-18 21:06 UTC, stefanrueger commented
> native ports

Aha, yes. My bad, the following corrects this
```
diff --git a/src/serialadapter.c b/src/serialadapter.c
index 5b649539..e17b7a22 100644
--- a/src/serialadapter.c
+++ b/src/serialadapter.c
@@ -122,7 +122,9 @@ static SERPORT *get_libserialport_data(int *np) {
     struct sp_port *p = port_list[i];
     char *q;
     // Fill sp struct with port information
-    if(sp_get_port_usb_vid_pid(p, &sp[j].vid, &sp[j].pid) == SP_OK && (q = sp_get_port_name(p))) {
+    if((q = sp_get_port_name(p))) {
+      if(sp_get_port_usb_vid_pid(p, &sp[j].vid, &sp[j].pid) != SP_OK)
+        sp[j].vid = sp[j].pid = 0;
       sp[j].port = cfg_strdup(__func__, q);
       sp[j].sernum = cfg_strdup(__func__, (q = sp_get_port_usb_serial(p))? q: "");
       j++;
```

If the native ports are printed, indeed, after reverting above maybe we can drop the output `Also note there may be other direct serial ports not listed above`?

2023-09-19 08:50 UTC, MCUdude commented
@stefanrueger we're almost there. The VID/PID shouldn't be printed for the `/dev/cu.Bluetooth-Incoming-Port` port

```
$ ./avrdude -curclock -patmega328p -P dunno
avrdude OS error: cannot open port dunno: No such file or directory
avrdude error: unable to open programmer urclock on port dunno
Possible candidate serial ports are:
  -P /dev/cu.Bluetooth-Incoming-Port or -P usb:0000:0000
  -P /dev/cu.UC-232AC or -P usb:0557:2008
  -P /dev/cu.usbmodem14102 or -P usb:03eb:2175
  -P /dev/cu.usbmodem1421402 or -P usb:03eb:2145
  -P /dev/cu.usbmodem1424201 or -P nano-every
  -P /dev/cu.usbmodem1424301 or -P usb:2341:0043
  -P /dev/cu.usbserial-14220 (via ch340 serial adapter)
  -P /dev/cu.usbserial-142130 (via ch340 serial adapter)
  -P /dev/cu.usbserial-142440 (via ch340 serial adapter)
  -P /dev/cu.usbserial-A50285BI, -P ft232r:A50285BI, -P 3d-printer:A50285BI or -P xmega-dev-board:A50285BI
  -P /dev/cu.usbserial-AH00M3HQ, -P ft232r:AH00M3HQ, -P 3d-printer:AH00M3HQ or -P xmega-dev-board:AH00M3HQ
  -P /dev/cu.usbserial-DN021PGG, -P ft231x, -P ft234x or -P ft230x
Note that above ports might not be connected to a target board or an AVR programmer.
Also note there may be other direct serial ports not listed above.

avrdude done.  Thank you.
```

2023-09-19 08:54 UTC, MCUdude commented
Wouldn't this be sufficient? After all, the PID can theoretically be zero, but the VID can't be.

```diff
diff --git a/src/serialadapter.c b/src/serialadapter.c
index e17b7a22..3ee356a0 100644
--- a/src/serialadapter.c
+++ b/src/serialadapter.c
@@ -251,7 +251,8 @@ static void sa_print_specs(const SERPORT *sp, int n, int i) {
 
   msg_warning("  -P %s", sp[i].port);
   for(char **Ps = Pspecs; *Ps; Ps++) {
-    msg_warning("%s %s", str_starts(*Ps, "(via ")? "": Ps[1]? ", -P": " or -P", *Ps);
+    if(sp[i].vid != 0)
+      msg_warning("%s %s", str_starts(*Ps, "(via ")? "": Ps[1]? ", -P": " or -P", *Ps);
     free(*Ps);
   }
   msg_warning("\n");
```

2023-09-19 09:04 UTC, MCUdude commented
> If the native ports are printed, indeed, after reverting above maybe we can drop the output Also note there may be other direct serial ports not listed above

> Also note there may be other direct serial ports not listed above.

I think it's smart to have the text there. Libserialport may not be able to find all ports for some reason. One known issue in MacOS is that liberserialport thinks that CH210x USB to serial adapters are _native_, and fail to list them. It only occurs on MacOS. See https://sigrok.org/bugzilla/show_bug.cgi?id=1698 for details. I hope it can be fixed soon. I was thinking about asking if there was any progress, but I can't create a bugzilla user; it looks like you'll have to be invited.

Anyways, this shouldn't be a showstopper for Avrdude, but it's good to know atleast.

2023-09-19 14:48 UTC, stefanrueger commented
> `-P usb:0000:0000`

How big a problem is this? The current code base will allow this port to be addressed through `-P usb:0:0`, so it might well be shown as an option. Note it is no longer offered when it wouldn't work (such as when *two* ports are there with 0:0 vid:pid) as you can see [above](https://github.com/avrdudes/avrdude/pull/1498#issuecomment-1725111872). If we don't print alternative `-P specs` for ports with 0 vid then users can no longer usefully give the internal serial port a short nickname in their .avrduderc (that would assign 0 vid and pid to it)

2023-09-19 17:02 UTC, MCUdude commented
> How big a problem is this?

It's not a  _big_ problem, but it technically isn't correct that a native serial port can be addressed via VID and PID numbers, since it isn't a USB device at all.

> Could you push the version you have tried for your latest tests?

I don't have any local changes to this PR other than the diff I suggested in a previous post.

> Feel free to go back to the drawing board and design a new PR.

Well, I'm happy with the result of this PR, and I'm keen to start working on something else. If you want to implement #1500, even by submitting a patch to this PR, I'm all for it. I have plenty of hardware I can use to test the "1200bps touch" functionality.

2023-09-19 20:00 UTC, stefanrueger commented
> [no] local changes to this PR

Are you sure? The output of your most recent tests *look like* they are sorted in the way that my patch to sort the list: [0001-Sort-list-of-plugged-in-SERPORTs-according-to-port.zip](https://github.com/avrdudes/avrdude/files/12653336/0001-Sort-list-of-plugged-in-SERPORTs-according-to-port.zip) patch would do it, but if I clone this PR the sorting isn't part of that (but I feel it should). Also the current PR has not reverted yet to the [previous way the SERPORT list would have been created](https://github.com/avrdudes/avrdude/pull/1498#issuecomment-1724415702). That too should be done before merging. 

As to `-P usb:0:0` I am OK either way (yes, it isn't a USB device but usb:0:0 doesn't look like a USB device b/c all is zero). If you don't want `-P usb:0:0` be printed then I would ever so slightly prefer
``` diff
diff --git a/src/serialadapter.c b/src/serialadapter.c
index e17b7a22..ef9396cc 100644
--- a/src/serialadapter.c
+++ b/src/serialadapter.c
@@ -232,7 +232,7 @@ static char **sa_list_specs(const SERPORT *sp, int n, int i) {
     }
   }
 
-  if(Pi == 0) {                 // No unique serial adapter, so maybe vid:pid[:sn] works?
+  if(Pi == 0 && sp[i].vid) {    // No unique serial adapter, so maybe vid:pid[:sn] works?
     if(sa_unique_by_ids(sp[i].vid, sp[i].pid, "", sp, n, i))
       Plist[Pi++] = str_sprintf("usb:%04x:%04x", sp[i].vid, sp[i].pid);
     else if(*sn && sa_unique_by_ids(sp[i].vid, sp[i].pid, sn, sp, n, i))
```

>  happy with the result of this PR

OK, how about you, @MCUdude,
 - Push the [sorting patch](https://github.com/avrdudes/avrdude/files/12653336/0001-Sort-list-of-plugged-in-SERPORTs-according-to-port.zip) into this PR
 - Push [changes that record native serial ports as well](https://github.com/avrdudes/avrdude/pull/1498#issuecomment-1724415702)
 - Solve the `P usb:0:0` issue as you see fit
 - If you think `str_endnumber()` is generally useful, maybe move it to `strutil.c` and advertise in `libavrdude.h`
 - Test the final PR (@mcuee as well?)

And once everyone is happy I merge the resulting PR.

> #1500
 
Defo not up my road. I don't know what should be done, and cannot test as I don't have the boards. I would (as with everything that I am asked to merge) look very carefully at any PR before merging.

2023-09-19 21:18 UTC, MCUdude commented
> Are you sure? 

Oh, sorry! I committed the changes, but I forgot to push them. Should be OK now.

> Push the [sorting patch](https://github.com/avrdudes/avrdude/files/12653336/0001-Sort-list-of-plugged-in-SERPORTs-according-to-port.zip) into this PR
Push https://github.com/avrdudes/avrdude/pull/1498#issuecomment-1724415702
Solve the P usb:0:0 issue as you see fit
If you think str_endnumber() is generally useful, maybe move it to strutil.c and advertise in libavrdude.h
Test the final PR (@mcuee as well?)

I've done every step in the list, and I'll do a final stress test before I go to bed.

> #1500
Defo not up my road. I don't know what should be done, and cannot test as I don't have the boards. I would (as with everything that I am asked to merge) look very carefully at any PR before merging.

No problem! I can start working on a proof of concept, submit a PR, and then we can take it from there.

2023-09-19 21:35 UTC, MCUdude commented
Here are some test results. Note that I've patched libserialport in order to work properly with the CP210x chip family. See [sigrokproject/libserialport#14](https://github.com/sigrokproject/libserialport/pull/14) for details.

```
$ cat ~/.avrduderc 
default_programmer = "usbasp";
default_serial     = "/dev/cu.usbserial-1410";
#allow_subshells    = yes;

serialadapter parent "ch340"
    id                     = "ch340-250k";
    baudrate               = 250000;
;

serialadapter parent "ch340"
    id                     = "ch340-500k";
    baudrate               = 500000;
;

serialadapter parent "ft232r"
    id                     = "3d-printer";
    usbsn                  = "A60408VE";
    baudrate               = 230400;
;

serialadapter parent "ft232r"
    id                     = "xmega-dev-board";
    baudrate               = 57600;
;

serialadapter
    id                     = "nano-every";
    desc                   = "Arduino Nano Every";
    usbvid                 = 0x2341;
    usbpid                 = 0x0058;
;

$ ./avrdude -curclock -patmega328p -P dunno
avrdude OS error: cannot open port dunno: No such file or directory
avrdude error: unable to open programmer urclock on port dunno
Possible candidate serial ports are:
  -P /dev/cu.Bluetooth-Incoming-Port
  -P /dev/cu.SLAB_USBtoUART or -P cp210x
  -P /dev/cu.UC-232AC or -P usb:0557:2008
  -P /dev/cu.usbmodem142201 or -P nano-every
  -P /dev/cu.usbmodem142301 or -P usb:2341:0043
  -P /dev/cu.usbmodem1424202 or -P usb:03eb:2145
  -P /dev/cu.usbmodem1424402 or -P usb:03eb:2175
  -P /dev/cu.usbserial-142140 (via ch340 serial adapter)
  -P /dev/cu.usbserial-142430 (via ch340 serial adapter)
  -P /dev/cu.usbserial-A50285BI, -P ft232r:A50285BI, -P 3d-printer:A50285BI or -P xmega-dev-board:A50285BI
  -P /dev/cu.usbserial-A60408VE, -P ft232r:A60408VE, -P 3d-printer or -P xmega-dev-board:A60408VE
  -P /dev/cu.usbserial-AH00M3HQ, -P ft232r:AH00M3HQ, -P 3d-printer:AH00M3HQ or -P xmega-dev-board:AH00M3HQ
Note that above ports might not be connected to a target board or an AVR programmer.
Also note there may be other direct serial ports not listed above.

avrdude done.  Thank you.

$ ./avrdude -curclock -patmega328p -P nano-every
avrdude warning: attempt 1 of 10: not in sync
avrdude warning: attempt 2 of 10: not in sync
avrdude warning: attempt 3 of 10: not in sync
^C

$ ./avrdude -curclock -patmega328p -P ch340
avrdude warning: -P ch340 is ambiguous; consider
  -P /dev/cu.usbserial-142140 (via ch340 serial adapter)
  -P /dev/cu.usbserial-142430 (via ch340 serial adapter)
avrdude OS error: cannot open port ch340: No such file or directory
avrdude error: unable to open programmer urclock on port ch340

avrdude done.  Thank you.

$ ./avrdude -curclock -patmega328p -P ft232r
avrdude warning: -P ft232r is ambiguous; consider
  -P /dev/cu.usbserial-A50285BI, -P ft232r:A50285BI, -P 3d-printer:A50285BI or -P xmega-dev-board:A50285BI
  -P /dev/cu.usbserial-A60408VE, -P ft232r:A60408VE, -P 3d-printer or -P xmega-dev-board:A60408VE
  -P /dev/cu.usbserial-AH00M3HQ, -P ft232r:AH00M3HQ, -P 3d-printer:AH00M3HQ or -P xmega-dev-board:AH00M3HQ
avrdude OS error: cannot open port ft232r: No such file or directory
avrdude error: unable to open programmer urclock on port ft232r

avrdude done.  Thank you.

$ ./avrdude -curclock -patmega328p -P 3d-printer
avrdude warning: attempt 1 of 10: not in sync
avrdude warning: attempt 2 of 10: not in sync
avrdude warning: attempt 3 of 10: not in sync
^C

$ ./avrdude -curclock -patmega328p -P ft232r:A
avrdude warning: -P ft232r:A is ambiguous; consider
  -P /dev/cu.usbserial-A50285BI, -P ft232r:A50285BI, -P 3d-printer:A50285BI or -P xmega-dev-board:A50285BI
  -P /dev/cu.usbserial-A60408VE, -P ft232r:A60408VE, -P 3d-printer or -P xmega-dev-board:A60408VE
  -P /dev/cu.usbserial-AH00M3HQ, -P ft232r:AH00M3HQ, -P 3d-printer:AH00M3HQ or -P xmega-dev-board:AH00M3HQ
avrdude OS error: cannot open port ft232r:A: No such file or directory
avrdude error: unable to open programmer urclock on port ft232r:A

avrdude done.  Thank you.

$ ./avrdude -curclock -patmega328p -P ft232r:...I
avrdude warning: attempt 1 of 10: not in sync
avrdude warning: attempt 2 of 10: not in sync
avrdude warning: attempt 3 of 10: not in sync
^C
```

2023-09-20 12:00 UTC, stefanrueger commented
It occurred to me that it might be nice to have an option `-P ?s` to list all curently plugged-in serial devices known to the libserialport library, and another option `-P ?sa` to list of all serial adapters known to AVRDUDE, i.e., defined in avrdude.conf.

```
$ avrdude -P ?s
Possible candidate serial ports are:
  -P /dev/ttyUSB0 or -P ft232r:A600K203
  -P /dev/ttyUSB1 or -P ft232r:MCU8
  -P /dev/ttyUSB3, -P ch340 or -P ch340-115k
Note that above ports might not be connected to a target board or an AVR programmer.
Also note there may be other direct serial ports not listed above.

$ avrdude -P ?sa
Valid serial adapters are:
  ch340      = [usbvid 0x1a86, usbpid 0x7523]
  ch340-115k = [usbvid 0x1a86, usbpid 0x7523]
  ch341a     = [usbvid 0x1a86, usbpid 0x5512]
  ch9102     = [usbvid 0x1a86, usbpid 0x55d4]
  cp210x     = [usbvid 0x10c4, usbpid 0xea60 0xea70 0xea71]
  ft2232h    = [usbvid 0x0403, usbpid 0x6010]
  ft231x     = [usbvid 0x0403, usbpid 0x6015]
  ft234x     = [usbvid 0x0403, usbpid 0x6015]
  ft230x     = [usbvid 0x0403, usbpid 0x6015]
  ft232h     = [usbvid 0x0403, usbpid 0x6014]
  ft232r     = [usbvid 0x0403, usbpid 0x6001]
  ft4232h    = [usbvid 0x0403, usbpid 0x6011]
  pl2303     = [usbvid 0x067b, usbpid 0x2303]
```

For simplicity, I have pushed this commit onto the current PR. I noted that `ft231x`, `ft234x` and `ft232h` share the same PID. Is this correct?

2023-09-20 12:32 UTC, MCUdude commented
> It occurred to me that it might be nice to have an option -P ?s to list all curently plugged-in serial devices known to the libserialport library, and another option -P ?sa to list of all serial adapters known to AVRDUDE, i.e., defined in avrdude.conf.

Great idea! I'll give it a try later this evening.

> I noted that ft231x, ft234x and ft232h share the same PID. Is this correct?

 ft231x, ft234x, and ft230x have the same PID. The ft232h has a different PID.

2023-09-22 22:21 UTC, merged