Fix permission denied error in linuxgpio programmer
avrdudes/avrdude pull request #917
Opened 2022-04-03 19:43 UTC by asmirnou

On Raspberry Pi using linuxgpio programmer without `sudo` fails with 
> Can't open gpioX/direction: Permission denied

The next attempt fails, because gpio pin remains exported and not removed. 

Open issue: #386

## Solution

After exporting gpio pin wait, until GPIO directory appears. Retry in case of EACCESS error while delayed udev permission rule applies. Call `unexport`, if `export` failed for whatever reason.

Verified that it fixes the problem.

2022-04-04 06:06 UTC, MCUdude commented
Thanks for the PR! I'm a pretty recent contributor, so @dl8dtl would have to have a look at this one.

[When searching for linuxgpio specific Avrdude issues](https://github.com/avrdudes/avrdude/issues?q=is%3Aissue+is%3Aopen+linuxgpio) it looks like there are released issues we well. You mentioned #386, but it looks to me like #472 and perhaps #372

2022-07-10 12:49 UTC, mcuee commented
This PR seems to help to avoid the issue.

```
pi@raspberrypi:~/Desktop/build/avr/avrdude_pr917/build_linux/src $ ./avrdude -C ./avrdude.conf -c linuxgpio -P GPIO -p m328p -U flash:w:./blinky_m328p.hex:i

avrdude: AVR device initialized and ready to accept instructions

Reading | ################################################## | 100% 0.00s

avrdude: Device signature = 0x1e950f (probably m328p)
avrdude: NOTE: "flash" memory has been specified, an erase cycle will be performed
         To disable this feature, specify the -D option.
avrdude: erasing chip
avrdude: reading input file "./blinky_m328p.hex"
avrdude: writing flash (32768 bytes):

Writing | ################################################## | 100% 7.75s

avrdude: 32768 bytes of flash written
avrdude: verifying flash memory against ./blinky_m328p.hex:

Reading | ################################################## | 100% 6.49s

avrdude: 32768 bytes of flash verified

avrdude done.  Thank you.


```

2022-07-10 12:51 UTC, mcuee commented
But if the issue already happened (say using master without the fix), then it will not help. 
```
pi@raspberrypi:~/Desktop/build/avr/avrdude/build_linux/src $ ./avrdude -C ./avrdude.conf -c linuxgpio 
-P GPIO -p m328p -U flash:w:./blinky_m328p.hex:i
Can't open gpioX/direction: Permission denied
avrdude: opening programmer "linuxgpio" on port "GPIO" failed

avrdude done.  Thank you.

pi@raspberrypi:~/Desktop/build/avr/avrdude/build_linux/src $ sudo ./avrdude -C ./avrdude.conf 
-c linuxgpio -P GPIO -p m328p -U flash:w:./blinky_m328p.hex:i
Can't export GPIO 25, already exported/busy?: Device or resource busyavrdude: opening programmer "linuxgpio" on port "GPIO" failed

avrdude done.  Thank you.


```

2022-07-10 12:55 UTC, mcuee commented
All in all, I think this PR is good to be merged. It at least helps to avoid the issue in the first place.

Moving to libgpiod may be the ultimate solution.
* https://github.com/avrdudes/avrdude/issues/831

2022-07-10 17:40 UTC, MCUdude commented
> Moving to libgpiod may be the ultimate solution. https://github.com/avrdudes/avrdude/issues/831

Absolutely! Now that libgpiod is a part of the linux kernel, it looks like libgpiod is available under /linux/gpio.h, which is how `linuxspi` interacts with the GPIO it uses as reset pin.

But I have no idea how to port the existing linuxgpio code over to libgpiod. Maybe the person who write linuxgpio in the first place would be interested to look into it?

2022-07-13 01:42 UTC, mcuee commented
@stefanrueger 
Maybe you can take a look at this one as well to see if this can be merged as it is. It seems to improve the situation of quite a few outstanding issues.

2022-09-21 16:01 UTC, stefanrueger requested changes
This is competently coded, well done.

Small comments:
```
         if (ret == 0) {
            break;
         } else if(...)
```
Whilst the code is not wrong, the `else` is not warranted, as `break` changes the flow of control. Below is arguably better readable:
```
  if(ret==0)
    break;

  if(...)
```

Using printf() a no-no. It is better to use the `avrdude_message()` system as it neatly considers the wanted verbosity and it prints to stderr, where all error and debug messages belong. I would change
```
if (retry_count > 1) {
  printf("Retrying...\n");
}
```
to
```
  if(retry_count > 1)
    avrdude_message(MSG_NOTICE2, "%s: retrying linuxgpio_dir_%s()\n", progname, i == PIN_AVR_MISO? "in": "out");
```
or something to that effect (untested).

2022-09-21 16:03 UTC, stefanrueger commented
I would be happy to merge the PR as @mcuee found it a useful improvement. The one request I have is to replace the `printf()` with an appropriate `avrdude_message()`.

2022-09-23 22:36 UTC, stefanrueger approved these changes

2022-09-24 12:21 UTC, merged